<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Optimization of sampling strata with the SamplingStrata package • SamplingStrata</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><link href="../extra.css" rel="stylesheet">
<meta property="og:title" content="Optimization of sampling strata with the SamplingStrata package">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">SamplingStrata</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">1.3.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/SamplingStrata.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/barcaroli/SamplingStrata">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Optimization of sampling strata with the SamplingStrata package</h1>
                        <h4 class="author">Giulio Barcaroli</h4>
            
            <h4 class="date">2018-10-11</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/barcaroli/SamplingStrata/blob/master/vignettes/SamplingStrata.Rmd"><code>vignettes/SamplingStrata.Rmd</code></a></small>
      <div class="hidden name"><code>SamplingStrata.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>Let us suppose we need to design a sample survey, having a complete frame containing information on the target population (identifiers plus auxiliary information). If our sample design is a stratified one, we need to choose how to form strata in the population, in order to get the maximum advantage by the available auxiliary information. In other words, we have to decide in which way to combine the values of the auxiliary variables (from now on, the ‘X’ variables) in order to determine a new variable, called ‘stratum’. To do so, we have to take into consideration the target variables of our sample survey (from now on, the ‘Y’ variables): if, to form strata, we choose the X variables most correlated to the Y’s, the efficiency of the samples drawn by the resulting stratified frame may be greatly increased. In order to handle the whole auxiliary information in a homogenous way, we have to reduce continuous data to categorical (by mean of a k-means clustering technique, for example). Then, for every set of candidate auxiliary variables X’s, we have to decide (i) what variables to consider as active variables in strata determination, and (ii) for each active variable, what set of values (in general, what aggregation of atomic values) have to be considered. Every combination of values of each active variable determine a particular stratification of the target population, i.e. a possible solution to the problem of ‘best’ stratification. Here, by best stratification, we mean the stratification that ensures the minimum sample cost, sufficient to satisfy a set of precision constraints, set on the accuracy of the estimates of the survey target variables Y’s (constraints expressed as maximum allowable sampling variance on estimates in different domains of interest). When the cost of data collection is uniform over the strata, then the total cost is directly proportional to the overall sample size, and the convenience of a particular stratification can be measured by the associated size of the sample, whose estimates are expected to satisfy given accuracy levels. This minimum size can be determined by applying the Bethel algorithm, with its Chromy variant. In general, the number of possible alternative stratifications for a given population may be very high, depending on the number of variables and on the number of their values, and in these cases it is not possible to enumerate them in order to assess the best one. A very convenient solution to this, is the adoption of the evolutionary approach, consisting in applying a genetic algorithm that may converge towards a near-optimal solution after a finite number of iterations. The methodology is fully described in <span class="citation">Ballin and Barcaroli (2013)</span>, and a complete illustration of the package, together with a comparison with the <em>stratification</em> package, is in <span class="citation">Barcaroli (2014)</span>. Also a complete application in a case of network data is reported in <span class="citation">Ballin and Barcaroli (2016)</span>. The implementation of the genetic algorithm is based on a modification of the functions in the <em>genalg</em> package <span class="citation">(see Willighagen 2005)</span>. In particular, the crossover operator ha been modified on the basis of the indications given by <span class="citation">O’Luing, Prestwich, and Tarim (2017)</span>.</p>
</div>
<div id="procedural-steps" class="section level1">
<h1 class="hasAnchor">
<a href="#procedural-steps" class="anchor"></a>Procedural steps</h1>
<p>The optimization of the sampling design starts by making the sampling frame available, defining the target estimates of the survey and establishing the precision constraints on them. It is then possible to determine the best stratification and the optimal allocation. Finally, we proceed with the selection of the sample. Formalizing, these are the required steps:</p>
<ul>
<li>analysis of the frame data: identification of available auxiliary information;</li>
<li>manipulation of auxiliary information: in case auxiliary variables are of the continuous type, they must be transformed into a categorical form;</li>
<li>construction of atomic strata: on the basis of the categorical auxiliary variables available in the sampling frame, a set of strata can be constructed by calculating the Cartesian product of the values of all the auxiliary variables;</li>
<li>characterization of each atomic stratum with the information related to the target variables: in order to optimise both strata and allocation of sampling units in strata, we need information on the distributions of the target variables (means and standard deviations) inside the different strata;</li>
<li>choice of the precision constraints for each target estimate, possibly differentiated by domain;</li>
<li>optimization of stratification and determination of required sample size and allocation in order to satisfy precision constraints on target estimates;</li>
<li>analysis of the resulting optimized strata;</li>
<li>association of new labels to sampling frame units, each of them indicating the new strata resulting by the optimal aggregation of the atomic strata;</li>
<li>selection of units from the sampling frame with a  selection scheme;</li>
<li>evaluation of the found optimal solution in terms of expected precision and bias.</li>
</ul>
<p>In the following, we will illustrate each step starting from a real sampling frame, the one that comes with the R package <em>sampling</em> (the dataframe <em>swissmunicipalities</em>).</p>
<div id="analysis-of-the-frame-data-and-manipulation-of-auxiliary-information" class="section level2">
<h2 class="hasAnchor">
<a href="#analysis-of-the-frame-data-and-manipulation-of-auxiliary-information" class="anchor"></a>Analysis of the frame data and manipulation of auxiliary information</h2>
<p>As a first step, we have to define a frame dataframe containing the following information:</p>
<ul>
<li>a unique identifier of the unit (no restriction on the name, may be ‘cod’);</li>
<li>the values of m auxiliary variables (named from X1 to Xm);</li>
<li>the (optional) values of p target variables (named from Y1 to Yp);</li>
<li>the value of the domain of interest for which we want to produce estimates (named ‘domainvalue’).</li>
</ul>
<p>By typing the following statements in the R environment:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(SamplingStrata)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="co">#&gt; Carico il pacchetto richiesto: memoise</span></a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="co">#&gt; Carico il pacchetto richiesto: doParallel</span></a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="co">#&gt; Carico il pacchetto richiesto: foreach</span></a>
<a class="sourceLine" id="cb1-5" data-line-number="5"><span class="co">#&gt; Carico il pacchetto richiesto: iterators</span></a>
<a class="sourceLine" id="cb1-6" data-line-number="6"><span class="co">#&gt; Carico il pacchetto richiesto: parallel</span></a>
<a class="sourceLine" id="cb1-7" data-line-number="7"><span class="co">#&gt; Carico il pacchetto richiesto: pbapply</span></a>
<a class="sourceLine" id="cb1-8" data-line-number="8"><span class="kw">require</span>(memoise)</a>
<a class="sourceLine" id="cb1-9" data-line-number="9"><span class="kw">data</span>(swissmunicipalities)</a></code></pre></div>
<p>we get the <em>swissmunicipalities</em> dataframe, that contains 2896 observations (each observation refers to a Swiss municipality). Among the others, there are the following variables (data are referred to 2003):</p>
<ul>
<li>REG: Swiss region</li>
<li>Nom: municipality name</li>
<li>Surfacesbois: wood area</li>
<li>Surfacescult: area under cultivation</li>
<li>Alp: mountain pasture area</li>
<li>Airbat: area with buildings</li>
<li>Airind: industrial area</li>
<li>Pop020: number of men and women aged between 0 and 19</li>
<li>Pop2040: number of men and women aged between 20 and 39</li>
<li>Pop4065: number of men and women aged between 40 and 64</li>
<li>Pop65P: number of men and women aged between 65 and over</li>
<li>POPTOT: total population</li>
</ul>
<p>Let us suppose we want to plan a survey whose target estimates are the totals of population by age class in each Swiss region. In this case, our Y variables will be:</p>
<ul>
<li>Y1: number of men and women aged between 0 and 19</li>
<li>Y2: number of men and women aged between 20 and 39</li>
<li>Y3: number of men and women aged between 40 and 64</li>
<li>Y4: number of men and women aged between 65 and over</li>
</ul>
<p>As for the auxiliary variables (X’s), we can use all of those characterising the area use (wood, mountain or pasture, cultivated, industrial, with buildings).</p>
<p>Finally, we want to produce estimates not only for the whole country, but also for each one of the seven different regions.</p>
<p>Function <em>buildFrameDF</em> permits to organize data in a suitable mode for next processing:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">swissmunicipalities<span class="op">$</span>id &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(swissmunicipalities))</a>
<a class="sourceLine" id="cb2-2" data-line-number="2">swissframe &lt;-<span class="st"> </span><span class="kw"><a href="../reference/buildFrameDF.html">buildFrameDF</a></span>(<span class="dt">df =</span> swissmunicipalities,</a>
<a class="sourceLine" id="cb2-3" data-line-number="3">                           <span class="dt">id =</span> <span class="st">"id"</span>,</a>
<a class="sourceLine" id="cb2-4" data-line-number="4">                           <span class="dt">X =</span> <span class="kw">c</span>(<span class="st">"POPTOT"</span>,</a>
<a class="sourceLine" id="cb2-5" data-line-number="5">                                 <span class="st">"Surfacesbois"</span>,</a>
<a class="sourceLine" id="cb2-6" data-line-number="6">                                 <span class="st">"Surfacescult"</span>,</a>
<a class="sourceLine" id="cb2-7" data-line-number="7">                                 <span class="st">"Alp"</span>,</a>
<a class="sourceLine" id="cb2-8" data-line-number="8">                                 <span class="st">"Airbat"</span>,</a>
<a class="sourceLine" id="cb2-9" data-line-number="9">                                 <span class="st">"Airind"</span>),</a>
<a class="sourceLine" id="cb2-10" data-line-number="10">                           <span class="dt">Y =</span> <span class="kw">c</span>(<span class="st">"Pop020"</span>,</a>
<a class="sourceLine" id="cb2-11" data-line-number="11">                                 <span class="st">"Pop2040"</span>,</a>
<a class="sourceLine" id="cb2-12" data-line-number="12">                                 <span class="st">"Pop4065"</span>,</a>
<a class="sourceLine" id="cb2-13" data-line-number="13">                                 <span class="st">"Pop65P"</span>),</a>
<a class="sourceLine" id="cb2-14" data-line-number="14">                           <span class="dt">domainvalue =</span> <span class="st">"REG"</span>)</a>
<a class="sourceLine" id="cb2-15" data-line-number="15"><span class="kw">str</span>(swissframe)</a>
<a class="sourceLine" id="cb2-16" data-line-number="16"><span class="co">#&gt; 'data.frame':    2896 obs. of  12 variables:</span></a>
<a class="sourceLine" id="cb2-17" data-line-number="17"><span class="co">#&gt;  $ id         : int  1 2 3 4 5 6 7 8 9 10 ...</span></a>
<a class="sourceLine" id="cb2-18" data-line-number="18"><span class="co">#&gt;  $ X1         : int  363273 177964 166558 128634 124914 90483 72626 59496 48655 40377 ...</span></a>
<a class="sourceLine" id="cb2-19" data-line-number="19"><span class="co">#&gt;  $ X2         : int  2326 67 97 1726 1635 2807 1139 408 976 425 ...</span></a>
<a class="sourceLine" id="cb2-20" data-line-number="20"><span class="co">#&gt;  $ X3         : int  967 31 93 1041 714 1827 1222 183 196 694 ...</span></a>
<a class="sourceLine" id="cb2-21" data-line-number="21"><span class="co">#&gt;  $ X4         : int  0 0 0 0 0 0 0 0 18 0 ...</span></a>
<a class="sourceLine" id="cb2-22" data-line-number="22"><span class="co">#&gt;  $ X5         : int  2884 773 1023 1070 856 972 812 524 463 523 ...</span></a>
<a class="sourceLine" id="cb2-23" data-line-number="23"><span class="co">#&gt;  $ X6         : int  260 60 213 212 64 238 134 27 108 137 ...</span></a>
<a class="sourceLine" id="cb2-24" data-line-number="24"><span class="co">#&gt;  $ Y1         : int  57324 32429 28161 19399 24291 18942 14337 9533 9127 8128 ...</span></a>
<a class="sourceLine" id="cb2-25" data-line-number="25"><span class="co">#&gt;  $ Y2         : int  131422 60074 50349 44263 44202 28958 24309 18843 14825 11265 ...</span></a>
<a class="sourceLine" id="cb2-26" data-line-number="26"><span class="co">#&gt;  $ Y3         : int  108178 57063 53734 39397 35421 27696 21334 18177 15140 13301 ...</span></a>
<a class="sourceLine" id="cb2-27" data-line-number="27"><span class="co">#&gt;  $ Y4         : int  66349 28398 34314 25575 21000 14887 12646 12943 9563 7683 ...</span></a>
<a class="sourceLine" id="cb2-28" data-line-number="28"><span class="co">#&gt;  $ domainvalue: int  4 1 3 2 1 4 5 6 2 2 ...</span></a></code></pre></div>
<p>As the X variables are of the continuous type, first we have to reduce them in a categorical (ordinal) form.</p>
<p>A suitable way to do so, is to apply a k-means clustering method <span class="citation">(see Hartigan and Wong 1979)</span> by using the function <em>var.bin</em>:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">library</span>(SamplingStrata)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2">swissframe<span class="op">$</span>X1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/var.bin.html">var.bin</a></span>(swissmunicipalities<span class="op">$</span>POPTOT, <span class="dt">bins=</span><span class="dv">18</span>)</a>
<a class="sourceLine" id="cb3-3" data-line-number="3">swissframe<span class="op">$</span>X2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/var.bin.html">var.bin</a></span>(swissmunicipalities<span class="op">$</span>Surfacesbois, <span class="dt">bins=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb3-4" data-line-number="4">swissframe<span class="op">$</span>X3 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/var.bin.html">var.bin</a></span>(swissmunicipalities<span class="op">$</span>Surfacescult, <span class="dt">bins=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb3-5" data-line-number="5">swissframe<span class="op">$</span>X4 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/var.bin.html">var.bin</a></span>(swissmunicipalities<span class="op">$</span>Alp, <span class="dt">bins=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb3-6" data-line-number="6">swissframe<span class="op">$</span>X5 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/var.bin.html">var.bin</a></span>(swissmunicipalities<span class="op">$</span>Airbat, <span class="dt">bins=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb3-7" data-line-number="7">swissframe<span class="op">$</span>X6 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/var.bin.html">var.bin</a></span>(swissmunicipalities<span class="op">$</span>Airind, <span class="dt">bins=</span><span class="dv">3</span>)</a></code></pre></div>
<p>Now, we have six different auxiliary variables of the categorical type, the first with 18 different modalities, the others with 3 modalities.</p>
<p>In any case, this dataframe comes with the package <em>SamplingStrata</em>: it can be made available by executing:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw">library</span>(SamplingStrata)</a>
<a class="sourceLine" id="cb4-2" data-line-number="2"><span class="kw">data</span>(swissframe)</a>
<a class="sourceLine" id="cb4-3" data-line-number="3"><span class="kw">head</span>(swissframe)</a>
<a class="sourceLine" id="cb4-4" data-line-number="4"><span class="co">#&gt;   progr REG X1 X2 X3 X4 X5 X6         id    Y1     Y2     Y3    Y4</span></a>
<a class="sourceLine" id="cb4-5" data-line-number="5"><span class="co">#&gt; 1     1   4 18  3  2  1  3  3     Zurich 57324 131422 108178 66349</span></a>
<a class="sourceLine" id="cb4-6" data-line-number="6"><span class="co">#&gt; 2     2   1 17  1  1  1  3  2     Geneve 32429  60074  57063 28398</span></a>
<a class="sourceLine" id="cb4-7" data-line-number="7"><span class="co">#&gt; 3     3   3 17  1  1  1  3  3      Basel 28161  50349  53734 34314</span></a>
<a class="sourceLine" id="cb4-8" data-line-number="8"><span class="co">#&gt; 4     4   2 17  2  3  1  3  3       Bern 19399  44263  39397 25575</span></a>
<a class="sourceLine" id="cb4-9" data-line-number="9"><span class="co">#&gt; 5     5   1 17  2  2  1  3  2   Lausanne 24291  44202  35421 21000</span></a>
<a class="sourceLine" id="cb4-10" data-line-number="10"><span class="co">#&gt; 6     6   4 16  3  3  1  3  3 Winterthur 18942  28958  27696 14887</span></a>
<a class="sourceLine" id="cb4-11" data-line-number="11"><span class="co">#&gt;   domainvalue</span></a>
<a class="sourceLine" id="cb4-12" data-line-number="12"><span class="co">#&gt; 1           4</span></a>
<a class="sourceLine" id="cb4-13" data-line-number="13"><span class="co">#&gt; 2           1</span></a>
<a class="sourceLine" id="cb4-14" data-line-number="14"><span class="co">#&gt; 3           3</span></a>
<a class="sourceLine" id="cb4-15" data-line-number="15"><span class="co">#&gt; 4           2</span></a>
<a class="sourceLine" id="cb4-16" data-line-number="16"><span class="co">#&gt; 5           1</span></a>
<a class="sourceLine" id="cb4-17" data-line-number="17"><span class="co">#&gt; 6           4</span></a></code></pre></div>
<p>We could also not indicate substantive X variables, if we want that each unit in the sampling frame be considered as an atomic stratum, and let to the optimization step to aggregate them on the basis of the values of the Y variable. In any case, as we have to indicate at least one X variable, we can use to this purpose the unique identifier in the frame:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">swissmunicipalities<span class="op">$</span>id &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(swissframe))</a>
<a class="sourceLine" id="cb5-2" data-line-number="2">newframe &lt;-<span class="st"> </span><span class="kw"><a href="../reference/buildFrameDF.html">buildFrameDF</a></span>(<span class="dt">df =</span> swissmunicipalities,</a>
<a class="sourceLine" id="cb5-3" data-line-number="3">                         <span class="dt">id =</span> <span class="st">"id"</span>,</a>
<a class="sourceLine" id="cb5-4" data-line-number="4">                         <span class="dt">X =</span> <span class="st">"id"</span>,</a>
<a class="sourceLine" id="cb5-5" data-line-number="5">                         <span class="dt">Y =</span> <span class="kw">c</span>(<span class="st">"Pop020"</span>,</a>
<a class="sourceLine" id="cb5-6" data-line-number="6">                               <span class="st">"Pop2040"</span>,</a>
<a class="sourceLine" id="cb5-7" data-line-number="7">                               <span class="st">"Pop4065"</span>,</a>
<a class="sourceLine" id="cb5-8" data-line-number="8">                               <span class="st">"Pop65P"</span>),</a>
<a class="sourceLine" id="cb5-9" data-line-number="9">                         <span class="dt">domainvalue =</span> <span class="st">"REG"</span>)</a>
<a class="sourceLine" id="cb5-10" data-line-number="10"><span class="kw">str</span>(newframe)</a>
<a class="sourceLine" id="cb5-11" data-line-number="11"><span class="co">#&gt; 'data.frame':    2896 obs. of  7 variables:</span></a>
<a class="sourceLine" id="cb5-12" data-line-number="12"><span class="co">#&gt;  $ id         : int  1 2 3 4 5 6 7 8 9 10 ...</span></a>
<a class="sourceLine" id="cb5-13" data-line-number="13"><span class="co">#&gt;  $ X1         : int  1 2 3 4 5 6 7 8 9 10 ...</span></a>
<a class="sourceLine" id="cb5-14" data-line-number="14"><span class="co">#&gt;  $ Y1         : int  57324 32429 28161 19399 24291 18942 14337 9533 9127 8128 ...</span></a>
<a class="sourceLine" id="cb5-15" data-line-number="15"><span class="co">#&gt;  $ Y2         : int  131422 60074 50349 44263 44202 28958 24309 18843 14825 11265 ...</span></a>
<a class="sourceLine" id="cb5-16" data-line-number="16"><span class="co">#&gt;  $ Y3         : int  108178 57063 53734 39397 35421 27696 21334 18177 15140 13301 ...</span></a>
<a class="sourceLine" id="cb5-17" data-line-number="17"><span class="co">#&gt;  $ Y4         : int  66349 28398 34314 25575 21000 14887 12646 12943 9563 7683 ...</span></a>
<a class="sourceLine" id="cb5-18" data-line-number="18"><span class="co">#&gt;  $ domainvalue: int  4 1 3 2 1 4 5 6 2 2 ...</span></a></code></pre></div>
</div>
<div id="construction-of-atomic-strata-and-association-of-the-information-related-to-target-variables" class="section level2">
<h2 class="hasAnchor">
<a href="#construction-of-atomic-strata-and-association-of-the-information-related-to-target-variables" class="anchor"></a>Construction of atomic strata and association of the information related to target variables</h2>
<p>The <em>strata</em> dataframe reports information regarding each atomic stratum in the population. There is one row for each stratum. The total number of strata is given by the number of different combinations of X’s values in the frame. For each stratum, the following information is required:</p>
<ul>
<li>the identifier of the stratum (named ‘stratum’ or ‘strato’), concatenation of the values of the X variables;</li>
<li>the values of the m auxiliary variables (named from X1 to Xm) corresponding to those in the frame;</li>
<li>the total number of units in the population (named ‘N’);</li>
<li>a flag (named ‘cens’) indicating if the stratum is to be censused (=1) or sampled (=0);</li>
<li>a variable indicating the cost of interviewing per unit in the stratum (named ‘cost’);</li>
<li>for each target variable y, its mean and standard deviation, named respectively ‘Mi’ and ‘Si’);</li>
<li>the value of the domain of interest to which the stratum belongs (‘DOM1’).</li>
</ul>
<p>For example:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw">data</span>(strata)</a>
<a class="sourceLine" id="cb6-2" data-line-number="2"><span class="kw">head</span>(strata)</a>
<a class="sourceLine" id="cb6-3" data-line-number="3"><span class="co">#&gt;   stratum    N  X1  X2  X3       M1       M2       S1       S2 cens cost</span></a>
<a class="sourceLine" id="cb6-4" data-line-number="4"><span class="co">#&gt; 1       1 2246 x11 x21 x31 148.1598 443.0137 95.41435 202.4569    0    1</span></a>
<a class="sourceLine" id="cb6-5" data-line-number="5"><span class="co">#&gt; 2       2 2972 x11 x21 x32 184.2041 513.8995 81.26956 214.9999    0    1</span></a>
<a class="sourceLine" id="cb6-6" data-line-number="6"><span class="co">#&gt; 3       3 1905 x11 x22 x31 193.8927 488.8046 79.66667 261.1876    0    1</span></a>
<a class="sourceLine" id="cb6-7" data-line-number="7"><span class="co">#&gt; 4       4 3125 x11 x22 x32 181.3437 597.1925 82.77032 226.5086    0    1</span></a>
<a class="sourceLine" id="cb6-8" data-line-number="8"><span class="co">#&gt; 5       5 1733 x12 x21 x31 109.9850 418.2234 88.20289 179.1571    0    1</span></a>
<a class="sourceLine" id="cb6-9" data-line-number="9"><span class="co">#&gt; 6       6 1060 x12 x21 x32 114.7943 489.8292 52.71574 166.0292    0    1</span></a>
<a class="sourceLine" id="cb6-10" data-line-number="10"><span class="co">#&gt;   DOM1</span></a>
<a class="sourceLine" id="cb6-11" data-line-number="11"><span class="co">#&gt; 1  tot</span></a>
<a class="sourceLine" id="cb6-12" data-line-number="12"><span class="co">#&gt; 2  tot</span></a>
<a class="sourceLine" id="cb6-13" data-line-number="13"><span class="co">#&gt; 3  tot</span></a>
<a class="sourceLine" id="cb6-14" data-line-number="14"><span class="co">#&gt; 4  tot</span></a>
<a class="sourceLine" id="cb6-15" data-line-number="15"><span class="co">#&gt; 5  tot</span></a>
<a class="sourceLine" id="cb6-16" data-line-number="16"><span class="co">#&gt; 6  tot</span></a></code></pre></div>
<p>If in the <em>frame</em> dataframe are also present the values of the target Y variables (from a census, or from administrative data), it is possible to automatically generate the <em>strata</em> dataframe by invoking the <em>buildStrataDF</em> function. Let us consider again the <em>swissframe</em> dataset that we have built in previous steps. To this dataset we can apply the function <em>buildStrataDF</em>:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">  swissstrata &lt;-<span class="st"> </span><span class="kw"><a href="../reference/buildStrataDF.html">buildStrataDF</a></span>(swissframe, <span class="dt">progress =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb7-2" data-line-number="2"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb7-3" data-line-number="3"><span class="co">#&gt; Computations are being done on population data</span></a>
<a class="sourceLine" id="cb7-4" data-line-number="4"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb7-5" data-line-number="5"><span class="co">#&gt; Number of strata:  641</span></a>
<a class="sourceLine" id="cb7-6" data-line-number="6"><span class="co">#&gt; ... of which with only one unit:  389</span></a></code></pre></div>
<p>This is the structure of the created dataframe:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="kw">head</span>(swissstrata)</a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="co">#&gt;        STRATO   N       M1        M2        M3       M4       S1       S2</span></a>
<a class="sourceLine" id="cb8-3" data-line-number="3"><span class="co">#&gt; 1 1*1*1*1*1*1 184 48.31522  49.40217  61.44022 28.40761 26.81536 28.49831</span></a>
<a class="sourceLine" id="cb8-4" data-line-number="4"><span class="co">#&gt; 2 1*1*1*1*1*2   1 98.00000 106.00000 116.00000 43.00000  0.00000  0.00000</span></a>
<a class="sourceLine" id="cb8-5" data-line-number="5"><span class="co">#&gt; 3 1*1*1*2*1*1   2 57.00000  64.00000  70.00000 50.00000  4.00000  0.00000</span></a>
<a class="sourceLine" id="cb8-6" data-line-number="6"><span class="co">#&gt; 4 1*1*2*1*1*1  11 77.72727  81.18182  92.36364 47.00000 15.24998 18.69768</span></a>
<a class="sourceLine" id="cb8-7" data-line-number="7"><span class="co">#&gt; 5 1*2*1*1*1*1   9 58.22222  61.55556  66.77778 36.22222 25.46360 20.27100</span></a>
<a class="sourceLine" id="cb8-8" data-line-number="8"><span class="co">#&gt; 6 1*2*1*2*1*1   8 61.00000  68.00000  84.62500 58.37500 24.56624 19.48076</span></a>
<a class="sourceLine" id="cb8-9" data-line-number="9"><span class="co">#&gt;         S3       S4 COST CENS DOM1 X1 X2 X3 X4 X5 X6</span></a>
<a class="sourceLine" id="cb8-10" data-line-number="10"><span class="co">#&gt; 1 32.63062 14.63922    1    0    1  1  1  1  1  1  1</span></a>
<a class="sourceLine" id="cb8-11" data-line-number="11"><span class="co">#&gt; 2  0.00000  0.00000    1    0    1  1  1  1  1  1  2</span></a>
<a class="sourceLine" id="cb8-12" data-line-number="12"><span class="co">#&gt; 3  1.00000 15.00000    1    0    1  1  1  1  2  1  1</span></a>
<a class="sourceLine" id="cb8-13" data-line-number="13"><span class="co">#&gt; 4 17.03084 11.12736    1    0    1  1  1  2  1  1  1</span></a>
<a class="sourceLine" id="cb8-14" data-line-number="14"><span class="co">#&gt; 5 24.89881 15.49751    1    0    1  1  2  1  1  1  1</span></a>
<a class="sourceLine" id="cb8-15" data-line-number="15"><span class="co">#&gt; 6 26.35307 26.55625    1    0    1  1  2  1  2  1  1</span></a></code></pre></div>
<p>It is worth while noting that the total number of different atomic strata is 641, lower than the dimension of the Cartesian product of the X’s (which is 4374): this is due to the fact that not all combinations of the value of the auxiliary variables are present in the sampling frame. Variables ‘cost’ and ‘cens’ are initialised respectively to 1 and 0 for all strata. It is possible to give them different values:</p>
<ul>
<li>for variable ‘cost’, it is possible to differentiate the cost of interviewing per unit by assigning real values;</li>
<li>for variable ‘cens’, it is possible to set it equal to 1 for all strata that are of the ‘take-all’ type (i.e. all units in that strata must be selected).</li>
</ul>
<p>The <em>swissstrata</em> dataframe comes together with <em>SamplingStrata</em> package, it can be made available by typing:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw">data</span>(swissstrata)</a></code></pre></div>
<p>On the contrary, if there is no information in the frame regarding the target variables, it is necessary to build the strata dataframe starting from other sources, for instance a previous round of the same survey, or from other surveys. In this case, we need to read sample data by executing:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">samp &lt;-<span class="st"> </span><span class="kw">read.delim</span>(<span class="st">"samplePrev.txt"</span>)</a></code></pre></div>
<p>The only difference is that computed mean and variances of the Y’s are sampling estimates, whose reliability should be evaluated by carefully considering their sampling variances. In addition to the naming constraints previously introduced, this case requires that a variable named ‘WEIGHT’ is present in the samp dataframe. Then we can execute this function in this way:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">strata &lt;-<span class="st"> </span><span class="kw"><a href="../reference/buildStrataDF.html">buildStrataDF</a></span>(samp)</a></code></pre></div>
<p>The result is much the same than in the previous case: the function creates a new dataframe, <em>strata</em>, and writes out in the working directory the strata file, named ‘strata.txt’.</p>
</div>
<div id="choice-of-the-precision-constraints-for-each-target-estimate" class="section level2">
<h2 class="hasAnchor">
<a href="#choice-of-the-precision-constraints-for-each-target-estimate" class="anchor"></a>Choice of the precision constraints for each target estimate</h2>
<p>The <em>errors</em> dataframe contains the accuracy constraints that are set on target estimates. This means to define a maximum coefficient of variation for each variable and for each domain value. Each row of this frame is related to accuracy constraints in a particular subdomain of interest, identified by the <em>domainvalue</em> value. In the case of the Swiss municipalities, we have chosen to define the following constraints:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw">data</span>(swisserrors)</a>
<a class="sourceLine" id="cb12-2" data-line-number="2">swisserrors</a>
<a class="sourceLine" id="cb12-3" data-line-number="3"><span class="co">#&gt;    DOM  CV1  CV2  CV3  CV4 domainvalue</span></a>
<a class="sourceLine" id="cb12-4" data-line-number="4"><span class="co">#&gt; 1 DOM1 0.08 0.12 0.08 0.12           1</span></a>
<a class="sourceLine" id="cb12-5" data-line-number="5"><span class="co">#&gt; 2 DOM1 0.08 0.12 0.08 0.12           2</span></a>
<a class="sourceLine" id="cb12-6" data-line-number="6"><span class="co">#&gt; 3 DOM1 0.08 0.12 0.08 0.12           3</span></a>
<a class="sourceLine" id="cb12-7" data-line-number="7"><span class="co">#&gt; 4 DOM1 0.08 0.12 0.08 0.12           4</span></a>
<a class="sourceLine" id="cb12-8" data-line-number="8"><span class="co">#&gt; 5 DOM1 0.08 0.12 0.08 0.12           5</span></a>
<a class="sourceLine" id="cb12-9" data-line-number="9"><span class="co">#&gt; 6 DOM1 0.08 0.12 0.08 0.12           6</span></a>
<a class="sourceLine" id="cb12-10" data-line-number="10"><span class="co">#&gt; 7 DOM1 0.08 0.12 0.08 0.12           7</span></a></code></pre></div>
<p>This example reports accuracy constraints on variables Y1, Y2, Y3 and Y4 that are the same for all the 7 different subdomains (Swiss regions) of domain level DOM1. Of course we can differentiate the precision constraints region by region. It is important to underline that the values of ‘domainvalue’ are the same than those in the <em>frame</em> dataframe, and correspond to the values of variable ‘DOM1’ in the strata dataframe. Once having defined dataframes containing frame data, strata information and precision constraints, it is worth while to check their internal and reciprocal coherence. It is possible to do that by using the function <em>checkInput</em>:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw"><a href="../reference/checkInput.html">checkInput</a></span>(<span class="dt">errors =</span> <span class="kw"><a href="../reference/checkInput.html">checkInput</a></span>(<span class="dt">errors =</span> swisserrors, </a>
<a class="sourceLine" id="cb13-2" data-line-number="2">                               <span class="dt">strata =</span> swissstrata, </a>
<a class="sourceLine" id="cb13-3" data-line-number="3">                               <span class="dt">sampframe =</span> swissframe))</a>
<a class="sourceLine" id="cb13-4" data-line-number="4"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb13-5" data-line-number="5"><span class="co">#&gt; Input data have been checked and are compliant with requirements</span></a>
<a class="sourceLine" id="cb13-6" data-line-number="6"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb13-7" data-line-number="7"><span class="co">#&gt; No input data indicated</span></a></code></pre></div>
<p>For instance, this function controls that the number of auxiliary variables is the same in the <em>frame</em> and in the <em>strata</em> dataframes; that the number of target variables indicated in the <em>frame</em> dataframe is the same than the number of means and standard deviations in the <em>strata</em> dataframe, and the same than the number of coefficient of variations indicated in the <em>errors</em> dataframe.</p>
<p>If we try to determine the total size of the sample required to satisfy these precision constraints, considering the current stratification of the frame (the 641 atomic strata), we can do it by simply using the function <em>bethel</em>. This function requires a slightly different specification of the constraints dataframe:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">cv &lt;-<span class="st"> </span>swisserrors[<span class="dv">1</span>,]</a>
<a class="sourceLine" id="cb14-2" data-line-number="2">cv</a>
<a class="sourceLine" id="cb14-3" data-line-number="3"><span class="co">#&gt;    DOM  CV1  CV2  CV3  CV4 domainvalue</span></a>
<a class="sourceLine" id="cb14-4" data-line-number="4"><span class="co">#&gt; 1 DOM1 0.08 0.12 0.08 0.12           1</span></a></code></pre></div>
<p>because the <em>bethel</em> function does not permit to differentiate precision constraints by subdomain. In any case, the result of the application of the Bethel algorithm [see bethel:1989] is:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">allocation &lt;-<span class="st"> </span><span class="kw"><a href="../reference/bethel.html">bethel</a></span>(swissstrata,cv)</a>
<a class="sourceLine" id="cb15-2" data-line-number="2"><span class="kw">sum</span>(allocation)</a>
<a class="sourceLine" id="cb15-3" data-line-number="3"><span class="co">#&gt; [1] 893</span></a></code></pre></div>
<p>That is, the required amount of units to be selected, with no optimization of sampling strata. In general, after the optimization, this number is sensibly reduced.</p>
</div>
<div id="optimization-of-frame-stratification" class="section level2">
<h2 class="hasAnchor">
<a href="#optimization-of-frame-stratification" class="anchor"></a>Optimization of frame stratification</h2>
<p>Once the strata and the constraints dataframes have been prepared, it is possible to apply the function that optimises the stratification of the frame, that is <em>optimizeStrata</em>. This function operates on all subdomains, identifying the best solution for each one of them. The fundamental parameters to be passed to optimizeStrata are:</p>
<ul>
<li>
<em>errors</em>: the (mandatory) dataframe containing the precision levels expressed in terms of maximum allowable coefficients of variation that regard the estimates on target variables of the survey;</li>
<li>
<em>strata</em>: the (mandatory) dataframe containing the information related to ‘atomic’ strata, i.e. the strata obtained by the Cartesian product of all auxiliary variables X’s. Information concerns the identifiability of strata (values of X’s) and variability of Y’s (for each Y, mean and standard deviation in strata);</li>
<li>
<em>cens</em>: the (optional) dataframe containing the ‘take-all’ strata, those strata whose units must be selected in whatever sample. It has same structure than *strata} dataframe;</li>
<li>
<em>strcens</em>: flag (TRUE/FALSE) to indicate if ‘take-all’ strata do exist or not. Default is FALSE;</li>
<li>
<em>initialStrata</em>: the initial limit on the number of strata for each solution. Default is NA, and in this case it is set equal to the number of atomic strata in each domain. If the parameter <em>addStrataFactor</em> is equal to zero, then <em>initialStrata</em> is equivalent to the maximum number of strata to be obtained in the final solution;</li>
<li>
<em>addStrataFactor</em>: indicates the probability that at each mutation the number of strata may increase with respect to the current value. Default is 0.0;</li>
<li>
<em>minnumstr</em>: indicates the minimum number of units that must be allocated in each stratum. Default is 2;</li>
<li>
<em>iter</em>: indicates the maximum number of iterations (= generations) of the genetic algorithm. Default is 50</li>
<li>
<em>pops</em>: dimension of each generations in terms of number 0f individuals to be generated. Default is 20;</li>
<li>
<em>mut_chance</em> (mutation chance): for each new individual, the probability to change each single chromosome, i.e. one bit of the solution vector. High values of this parameter allow a deeper exploration of the solution space, but a slower convergence, while low values permit a faster convergence, but the final solution can be distant from the optimal one. Default is NA, in correspondence of which it is computed as 1/(vars+1) where vars is the length of elements in the solution;</li>
<li>
<em>elitism_rate</em>: indicates the rate of better solutions that must be preserved from one generation to another. Default is 0.2;</li>
<li>
<em>suggestions</em>: indicates one possible solution (from kmeans clustering or from previous runs) that will be introduced in the initial population. Default is NULL;</li>
<li>
<em>realAllocation</em> : if FALSE, the allocation is based on INTEGER values; if TRUE, the allocation is based on REAL values. Default is TRUE;</li>
<li>
<em>writeFiles</em> : indicates if the various dataframes and plots produced during the execution have to be written in the working directory /output. Default is FALSE;</li>
<li>
<em>showPlot</em> : indicates if the plot showing the trend in the value of the objective function has to be shown or not. In parallel = TRUE, this defaults to FALSE, otherwise default is TRUE.</li>
<li>
<em>parallel</em> : Should the analysis be run in parallel. Default is TRUE</li>
<li>
<em>cores</em> : if the analysis is run in parallel, how many cores should be used. If not specified n-1 of total available cores are used OR if number of domains &lt; (n-1) cores, then number of cores equal to number of domains are used</li>
</ul>
<p>In the case of the Swiss municipalities, we can use almost all of default values for parameters with the exception of the errors and strata dataframes, and for the option ‘writeFiles’:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">solution &lt;-<span class="st"> </span><span class="kw"><a href="../reference/optimizeStrata.html">optimizeStrata</a></span>(</a>
<a class="sourceLine" id="cb16-2" data-line-number="2">    <span class="dt">errors =</span> swisserrors, </a>
<a class="sourceLine" id="cb16-3" data-line-number="3">    <span class="dt">strata =</span> swissstrata,</a>
<a class="sourceLine" id="cb16-4" data-line-number="4">    <span class="dt">parallel =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb16-5" data-line-number="5">    <span class="dt">writeFiles =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb16-6" data-line-number="6">    <span class="dt">showPlot =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb16-7" data-line-number="7"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb16-8" data-line-number="8"><span class="co">#&gt;  *** Domain :  1   1</span></a>
<a class="sourceLine" id="cb16-9" data-line-number="9"><span class="co">#&gt;  Number of strata :  119</span></a>
<a class="sourceLine" id="cb16-10" data-line-number="10"><span class="co">#&gt; ---------------------------------------------</span></a>
<a class="sourceLine" id="cb16-11" data-line-number="11"><span class="co">#&gt; Optimal stratification with Genetic Algorithm</span></a>
<a class="sourceLine" id="cb16-12" data-line-number="12"><span class="co">#&gt; ---------------------------------------------</span></a>
<a class="sourceLine" id="cb16-13" data-line-number="13"><span class="co">#&gt;  *** Parameters ***</span></a>
<a class="sourceLine" id="cb16-14" data-line-number="14"><span class="co">#&gt; ---------------------------</span></a>
<a class="sourceLine" id="cb16-15" data-line-number="15"><span class="co">#&gt; Domain:  1</span></a>
<a class="sourceLine" id="cb16-16" data-line-number="16"><span class="co">#&gt; Maximum number of strata:  119</span></a>
<a class="sourceLine" id="cb16-17" data-line-number="17"><span class="co">#&gt; Minimum number of units per stratum:  2</span></a>
<a class="sourceLine" id="cb16-18" data-line-number="18"><span class="co">#&gt; Take-all strata (TRUE/FALSE):  FALSE</span></a>
<a class="sourceLine" id="cb16-19" data-line-number="19"><span class="co">#&gt; number of sampling strata :  119</span></a>
<a class="sourceLine" id="cb16-20" data-line-number="20"><span class="co">#&gt; Number of target variables:  4</span></a>
<a class="sourceLine" id="cb16-21" data-line-number="21"><span class="co">#&gt; Number of domains:  1</span></a>
<a class="sourceLine" id="cb16-22" data-line-number="22"><span class="co">#&gt; Number of GA iterations:  50</span></a>
<a class="sourceLine" id="cb16-23" data-line-number="23"><span class="co">#&gt; Dimension of GA population:  20</span></a>
<a class="sourceLine" id="cb16-24" data-line-number="24"><span class="co">#&gt; Mutation chance in GA generation:  NA</span></a>
<a class="sourceLine" id="cb16-25" data-line-number="25"><span class="co">#&gt; Elitism rate in GA generation:  0.2</span></a>
<a class="sourceLine" id="cb16-26" data-line-number="26"><span class="co">#&gt; Chance to add strata to maximum:  0</span></a>
<a class="sourceLine" id="cb16-27" data-line-number="27"><span class="co">#&gt; Allocation with real numbers instead of integers:  TRUE</span></a>
<a class="sourceLine" id="cb16-28" data-line-number="28"><span class="co">#&gt;  *** Sample cost:  32.61629</span></a>
<a class="sourceLine" id="cb16-29" data-line-number="29"><span class="co">#&gt;  *** Number of strata:  14</span></a></code></pre></div>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-16-1.png" width="700"></p>
<pre><code>#&gt; 
#&gt;  *** Domain :  2   2
#&gt;  Number of strata :  127
#&gt; ---------------------------------------------
#&gt; Optimal stratification with Genetic Algorithm
#&gt; ---------------------------------------------
#&gt;  *** Parameters ***
#&gt; ---------------------------
#&gt; Domain:  2
#&gt; Maximum number of strata:  127
#&gt; Minimum number of units per stratum:  2
#&gt; Take-all strata (TRUE/FALSE):  FALSE
#&gt; number of sampling strata :  127
#&gt; Number of target variables:  4
#&gt; Number of domains:  1
#&gt; Number of GA iterations:  50
#&gt; Dimension of GA population:  20
#&gt; Mutation chance in GA generation:  NA
#&gt; Elitism rate in GA generation:  0.2
#&gt; Chance to add strata to maximum:  0
#&gt; Allocation with real numbers instead of integers:  TRUE
#&gt;  *** Sample cost:  38.98177
#&gt;  *** Number of strata:  13</code></pre>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-16-2.png" width="700"></p>
<pre><code>#&gt; 
#&gt;  *** Domain :  3   3
#&gt;  Number of strata :  61
#&gt; ---------------------------------------------
#&gt; Optimal stratification with Genetic Algorithm
#&gt; ---------------------------------------------
#&gt;  *** Parameters ***
#&gt; ---------------------------
#&gt; Domain:  3
#&gt; Maximum number of strata:  61
#&gt; Minimum number of units per stratum:  2
#&gt; Take-all strata (TRUE/FALSE):  FALSE
#&gt; number of sampling strata :  61
#&gt; Number of target variables:  4
#&gt; Number of domains:  1
#&gt; Number of GA iterations:  50
#&gt; Dimension of GA population:  20
#&gt; Mutation chance in GA generation:  NA
#&gt; Elitism rate in GA generation:  0.2
#&gt; Chance to add strata to maximum:  0
#&gt; Allocation with real numbers instead of integers:  TRUE
#&gt;  *** Sample cost:  17.33092
#&gt;  *** Number of strata:  8</code></pre>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-16-3.png" width="700"></p>
<pre><code>#&gt; 
#&gt;  *** Domain :  4   4
#&gt;  Number of strata :  60
#&gt; ---------------------------------------------
#&gt; Optimal stratification with Genetic Algorithm
#&gt; ---------------------------------------------
#&gt;  *** Parameters ***
#&gt; ---------------------------
#&gt; Domain:  4
#&gt; Maximum number of strata:  60
#&gt; Minimum number of units per stratum:  2
#&gt; Take-all strata (TRUE/FALSE):  FALSE
#&gt; number of sampling strata :  60
#&gt; Number of target variables:  4
#&gt; Number of domains:  1
#&gt; Number of GA iterations:  50
#&gt; Dimension of GA population:  20
#&gt; Mutation chance in GA generation:  NA
#&gt; Elitism rate in GA generation:  0.2
#&gt; Chance to add strata to maximum:  0
#&gt; Allocation with real numbers instead of integers:  TRUE
#&gt;  *** Sample cost:  18.41202
#&gt;  *** Number of strata:  6</code></pre>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-16-4.png" width="700"></p>
<pre><code>#&gt; 
#&gt;  *** Domain :  5   5
#&gt;  Number of strata :  134
#&gt; ---------------------------------------------
#&gt; Optimal stratification with Genetic Algorithm
#&gt; ---------------------------------------------
#&gt;  *** Parameters ***
#&gt; ---------------------------
#&gt; Domain:  5
#&gt; Maximum number of strata:  134
#&gt; Minimum number of units per stratum:  2
#&gt; Take-all strata (TRUE/FALSE):  FALSE
#&gt; number of sampling strata :  134
#&gt; Number of target variables:  4
#&gt; Number of domains:  1
#&gt; Number of GA iterations:  50
#&gt; Dimension of GA population:  20
#&gt; Mutation chance in GA generation:  NA
#&gt; Elitism rate in GA generation:  0.2
#&gt; Chance to add strata to maximum:  0
#&gt; Allocation with real numbers instead of integers:  TRUE
#&gt;  *** Sample cost:  45.75451
#&gt;  *** Number of strata:  19</code></pre>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-16-5.png" width="700"></p>
<pre><code>#&gt; 
#&gt;  *** Domain :  6   6
#&gt;  Number of strata :  100
#&gt; ---------------------------------------------
#&gt; Optimal stratification with Genetic Algorithm
#&gt; ---------------------------------------------
#&gt;  *** Parameters ***
#&gt; ---------------------------
#&gt; Domain:  6
#&gt; Maximum number of strata:  100
#&gt; Minimum number of units per stratum:  2
#&gt; Take-all strata (TRUE/FALSE):  FALSE
#&gt; number of sampling strata :  100
#&gt; Number of target variables:  4
#&gt; Number of domains:  1
#&gt; Number of GA iterations:  50
#&gt; Dimension of GA population:  20
#&gt; Mutation chance in GA generation:  NA
#&gt; Elitism rate in GA generation:  0.2
#&gt; Chance to add strata to maximum:  0
#&gt; Allocation with real numbers instead of integers:  TRUE
#&gt;  *** Sample cost:  29.85364
#&gt;  *** Number of strata:  12</code></pre>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-16-6.png" width="700"></p>
<pre><code>#&gt; 
#&gt;  *** Domain :  7   7
#&gt;  Number of strata :  40
#&gt; ---------------------------------------------
#&gt; Optimal stratification with Genetic Algorithm
#&gt; ---------------------------------------------
#&gt;  *** Parameters ***
#&gt; ---------------------------
#&gt; Domain:  7
#&gt; Maximum number of strata:  40
#&gt; Minimum number of units per stratum:  2
#&gt; Take-all strata (TRUE/FALSE):  FALSE
#&gt; number of sampling strata :  40
#&gt; Number of target variables:  4
#&gt; Number of domains:  1
#&gt; Number of GA iterations:  50
#&gt; Dimension of GA population:  20
#&gt; Mutation chance in GA generation:  NA
#&gt; Elitism rate in GA generation:  0.2
#&gt; Chance to add strata to maximum:  0
#&gt; Allocation with real numbers instead of integers:  TRUE
#&gt;  *** Sample cost:  18.46616
#&gt;  *** Number of strata:  8</code></pre>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-16-7.png" width="700"></p>
<pre><code>#&gt; 
#&gt;  *** Sample size :  202
#&gt;  *** Number of strata :  80
#&gt; ---------------------------</code></pre>
<p>Note that by so doing the <em>initialStrata</em> parameter is set equal to the number of atomic strata in each domain . Another possibility is to set a pre-determined value for each domain, for instance equal in each domain, as c(5,5,5,5,5,5,5,5).</p>
<p>The execution of <em>optimizeStrata</em> produces the solution of 7 different optimization problems, one for each domain.</p>
<p>The graphs illustrate the convergence of the solution to the final one starting from the initial one (i.e. the one related to the atomic strata). Along the x-axis are reported the executed iterations, from 1 to the maximum, while on the y-axis are reported the size of the sample required to satisfy precision constraints. The upper (red) line represent the average sample size for each iteration, while the lower (black) line represents the best solution found until the i-th iteration.</p>
<p>The results of the execution are contained in the list ‘solution’, composed by two elements:</p>
<ol style="list-style-type: decimal">
<li>
<em>solution$indices</em>: the vector of the indices that indicates to what aggregated stratum each atomic stratum belongs;</li>
<li>
<em>solution$aggr_strata</em>: the dataframe containing information on the optimal aggregated strata.</li>
</ol>
<p>We can calculate the expected CV’s by executing the function:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="kw"><a href="../reference/expected_CV.html">expected_CV</a></span>(solution<span class="op">$</span>aggr_strata)</a>
<a class="sourceLine" id="cb24-2" data-line-number="2"><span class="co">#&gt;      cv(Y1) cv(Y2) cv(Y3) cv(Y4)</span></a>
<a class="sourceLine" id="cb24-3" data-line-number="3"><span class="co">#&gt; DOM1  0.076  0.070  0.070  0.077</span></a>
<a class="sourceLine" id="cb24-4" data-line-number="4"><span class="co">#&gt; DOM2  0.078  0.081  0.079  0.088</span></a>
<a class="sourceLine" id="cb24-5" data-line-number="5"><span class="co">#&gt; DOM3  0.078  0.077  0.078  0.096</span></a>
<a class="sourceLine" id="cb24-6" data-line-number="6"><span class="co">#&gt; DOM4  0.078  0.073  0.079  0.087</span></a>
<a class="sourceLine" id="cb24-7" data-line-number="7"><span class="co">#&gt; DOM5  0.076  0.079  0.077  0.077</span></a>
<a class="sourceLine" id="cb24-8" data-line-number="8"><span class="co">#&gt; DOM6  0.078  0.077  0.077  0.082</span></a>
<a class="sourceLine" id="cb24-9" data-line-number="9"><span class="co">#&gt; DOM7  0.077  0.079  0.075  0.091</span></a></code></pre></div>
<p>and compare them to the set of precision constraints in order to verify the compliance:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1">swisserrors</a>
<a class="sourceLine" id="cb25-2" data-line-number="2"><span class="co">#&gt;    DOM  CV1  CV2  CV3  CV4 domainvalue</span></a>
<a class="sourceLine" id="cb25-3" data-line-number="3"><span class="co">#&gt; 1 DOM1 0.08 0.12 0.08 0.12           1</span></a>
<a class="sourceLine" id="cb25-4" data-line-number="4"><span class="co">#&gt; 2 DOM1 0.08 0.12 0.08 0.12           2</span></a>
<a class="sourceLine" id="cb25-5" data-line-number="5"><span class="co">#&gt; 3 DOM1 0.08 0.12 0.08 0.12           3</span></a>
<a class="sourceLine" id="cb25-6" data-line-number="6"><span class="co">#&gt; 4 DOM1 0.08 0.12 0.08 0.12           4</span></a>
<a class="sourceLine" id="cb25-7" data-line-number="7"><span class="co">#&gt; 5 DOM1 0.08 0.12 0.08 0.12           5</span></a>
<a class="sourceLine" id="cb25-8" data-line-number="8"><span class="co">#&gt; 6 DOM1 0.08 0.12 0.08 0.12           6</span></a>
<a class="sourceLine" id="cb25-9" data-line-number="9"><span class="co">#&gt; 7 DOM1 0.08 0.12 0.08 0.12           7</span></a></code></pre></div>
</div>
</div>
<div id="initial-solution-with-kmeans-clustering-of-atomic-strata" class="section level1">
<h1 class="hasAnchor">
<a href="#initial-solution-with-kmeans-clustering-of-atomic-strata" class="anchor"></a>Initial solution with kmeans clustering of atomic strata</h1>
<p>In order to speed up the convergence towards the optimal solution, an initial one can be given as a “suggestion” to ‘optimizeStrata’ function. The function <em>KmeansSolution</em> produces this initial solution by clustering atomic strata considering the values of the means of all the target variables Y.</p>
<p>Also, the optimal number of clusters is determined inside each domain. If the default value for nstrata is used, then the number of aggregate strata is optimized by varying the number of cluster from 2 to number of atomic strata in each domain, divided by 2. Otherwise, it is possible to indicate a fixed number of aggregate strata to be obtained.</p>
<p>Other parameters are:</p>
<ul>
<li>
<em>minnumstrat</em>: the minimum number of units to be allocated in each stratum(default is 2);</li>
<li>
<em>maxcluster</em>: the maximum number of clusters to be considered in the execution of kmeans algorithm;</li>
<li>
<em>showPlot</em>: if TRUE, allows to visualise the optimization.</li>
</ul>
<p>For any given number of clusters, the correspondent aggregation of atomic strata is considered as input to the function ‘bethel’. The number of clusters for which the value of the sample size necessary to fulfil precision constraints is the minimum one, is retained as the optimal one.</p>
<p>The overall solution is obtained by concatenating optimal clusters obtained in domains. The result is a dataframe with two columns: the first indicates the clusters, the second the domains:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1">solutionKmeans1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/KmeansSolution.html">KmeansSolution</a></span>(swissstrata,</a>
<a class="sourceLine" id="cb26-2" data-line-number="2">                                   swisserrors,</a>
<a class="sourceLine" id="cb26-3" data-line-number="3">                                   <span class="dt">nstrata=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb26-4" data-line-number="4">                                   <span class="dt">minnumstrat=</span><span class="dv">2</span>,</a>
<a class="sourceLine" id="cb26-5" data-line-number="5">                                   <span class="dt">maxclusters=</span><span class="ot">NA</span>,</a>
<a class="sourceLine" id="cb26-6" data-line-number="6">                                   <span class="dt">showPlot=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb26-7" data-line-number="7"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb26-8" data-line-number="8"><span class="co">#&gt; -----------------</span></a>
<a class="sourceLine" id="cb26-9" data-line-number="9"><span class="co">#&gt;  Kmeans solution </span></a>
<a class="sourceLine" id="cb26-10" data-line-number="10"><span class="co">#&gt; -----------------</span></a>
<a class="sourceLine" id="cb26-11" data-line-number="11"><span class="co">#&gt;  *** Domain:  1  ***</span></a>
<a class="sourceLine" id="cb26-12" data-line-number="12"><span class="co">#&gt;  Number of strata:  9</span></a>
<a class="sourceLine" id="cb26-13" data-line-number="13"><span class="co">#&gt;  Sample size     :  18</span></a>
<a class="sourceLine" id="cb26-14" data-line-number="14"><span class="co">#&gt;  *** Domain:  2  ***</span></a>
<a class="sourceLine" id="cb26-15" data-line-number="15"><span class="co">#&gt;  Number of strata:  9</span></a>
<a class="sourceLine" id="cb26-16" data-line-number="16"><span class="co">#&gt;  Sample size     :  17</span></a>
<a class="sourceLine" id="cb26-17" data-line-number="17"><span class="co">#&gt;  *** Domain:  3  ***</span></a>
<a class="sourceLine" id="cb26-18" data-line-number="18"><span class="co">#&gt;  Number of strata:  7</span></a>
<a class="sourceLine" id="cb26-19" data-line-number="19"><span class="co">#&gt;  Sample size     :  13</span></a>
<a class="sourceLine" id="cb26-20" data-line-number="20"><span class="co">#&gt;  *** Domain:  4  ***</span></a>
<a class="sourceLine" id="cb26-21" data-line-number="21"><span class="co">#&gt;  Number of strata:  6</span></a>
<a class="sourceLine" id="cb26-22" data-line-number="22"><span class="co">#&gt;  Sample size     :  10</span></a>
<a class="sourceLine" id="cb26-23" data-line-number="23"><span class="co">#&gt;  *** Domain:  5  ***</span></a>
<a class="sourceLine" id="cb26-24" data-line-number="24"><span class="co">#&gt;  Number of strata:  7</span></a>
<a class="sourceLine" id="cb26-25" data-line-number="25"><span class="co">#&gt;  Sample size     :  13</span></a>
<a class="sourceLine" id="cb26-26" data-line-number="26"><span class="co">#&gt;  *** Domain:  6  ***</span></a>
<a class="sourceLine" id="cb26-27" data-line-number="27"><span class="co">#&gt;  Number of strata:  7</span></a>
<a class="sourceLine" id="cb26-28" data-line-number="28"><span class="co">#&gt;  Sample size     :  13</span></a>
<a class="sourceLine" id="cb26-29" data-line-number="29"><span class="co">#&gt;  *** Domain:  7  ***</span></a>
<a class="sourceLine" id="cb26-30" data-line-number="30"><span class="co">#&gt;  Number of strata:  7</span></a>
<a class="sourceLine" id="cb26-31" data-line-number="31"><span class="co">#&gt;  Sample size     :  15</span></a>
<a class="sourceLine" id="cb26-32" data-line-number="32"><span class="kw">head</span>(solutionKmeans1)</a>
<a class="sourceLine" id="cb26-33" data-line-number="33"><span class="co">#&gt;   suggestions domainvalue</span></a>
<a class="sourceLine" id="cb26-34" data-line-number="34"><span class="co">#&gt; 1           6           1</span></a>
<a class="sourceLine" id="cb26-35" data-line-number="35"><span class="co">#&gt; 2           6           1</span></a>
<a class="sourceLine" id="cb26-36" data-line-number="36"><span class="co">#&gt; 3           6           1</span></a>
<a class="sourceLine" id="cb26-37" data-line-number="37"><span class="co">#&gt; 4           6           1</span></a>
<a class="sourceLine" id="cb26-38" data-line-number="38"><span class="co">#&gt; 5           6           1</span></a>
<a class="sourceLine" id="cb26-39" data-line-number="39"><span class="co">#&gt; 6           6           1</span></a></code></pre></div>
<p>This solution can be given as argument to the parameter <em>suggestion</em> in the <em>optimizeStrata</em> function:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1">solution_with_kmeans &lt;-<span class="st"> </span><span class="kw"><a href="../reference/optimizeStrata.html">optimizeStrata</a></span>(</a>
<a class="sourceLine" id="cb27-2" data-line-number="2">    <span class="dt">errors =</span> swisserrors,</a>
<a class="sourceLine" id="cb27-3" data-line-number="3">    <span class="dt">strata =</span> swissstrata,</a>
<a class="sourceLine" id="cb27-4" data-line-number="4">    <span class="dt">suggestions =</span> solutionKmeans1,</a>
<a class="sourceLine" id="cb27-5" data-line-number="5">    <span class="dt">parallel =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb27-6" data-line-number="6">    <span class="dt">writeFiles =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb27-7" data-line-number="7">    <span class="dt">showPlot =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb27-8" data-line-number="8"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb27-9" data-line-number="9"><span class="co">#&gt;  *** Domain :  1   1</span></a>
<a class="sourceLine" id="cb27-10" data-line-number="10"><span class="co">#&gt;  Number of strata :  119</span></a>
<a class="sourceLine" id="cb27-11" data-line-number="11"><span class="co">#&gt; GA Settings</span></a>
<a class="sourceLine" id="cb27-12" data-line-number="12"><span class="co">#&gt;   Population size       = 20</span></a>
<a class="sourceLine" id="cb27-13" data-line-number="13"><span class="co">#&gt;   Number of Generations = 50</span></a>
<a class="sourceLine" id="cb27-14" data-line-number="14"><span class="co">#&gt;   Elitism               = 4</span></a>
<a class="sourceLine" id="cb27-15" data-line-number="15"><span class="co">#&gt;   Mutation Chance       = 0.00833333333333333</span></a>
<a class="sourceLine" id="cb27-16" data-line-number="16"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb27-17" data-line-number="17"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb27-18" data-line-number="18"><span class="co">#&gt; Suggestions</span></a>
<a class="sourceLine" id="cb27-19" data-line-number="19"><span class="co">#&gt;   1 = (6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 9, 9, 9, 9, 8, 8, 6, 6, 6, 6, 6, 6, 6, 2, 2, 6, 2, 2, 2, 2, 2, 2, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 7, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5)</span></a></code></pre></div>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1"><span class="kw">sum</span>(<span class="kw">ceiling</span>(solution_with_kmeans<span class="op">$</span>aggr_strata<span class="op">$</span>SOLUZ))</a>
<a class="sourceLine" id="cb28-2" data-line-number="2"><span class="co">#&gt; [1] 96</span></a></code></pre></div>
<p>thus obtaining a much more conventient solution than the one without the kmeans suggestion, with the same number of iterations.</p>
</div>
<div id="adjustment-of-the-final-sampling-size" class="section level1">
<h1 class="hasAnchor">
<a href="#adjustment-of-the-final-sampling-size" class="anchor"></a>Adjustment of the final sampling size</h1>
<p>After the optimization step, the final sample size is the result of the allocation of units in final strata. This allocation is such that the precision constraints are expected to be satisfied. Actually, three possible situations may occur:</p>
<ul>
<li>the resulting sample size is acceptable;</li>
<li>the resulting sample size is to high, it is not affordable with respect to the available budget;</li>
<li>the resulting sample size is too low, the available budget permits to increase the number of units.</li>
</ul>
<p>In the first case, no action is required. In the second case, it is necessary to reduce the number of units, by equally applying the same reduction rate in each stratum. In the third case, we could either to set more tight precision constraints, or proceed to increase the sample size by applying the same increase rate in each stratum. This increase/reduction process is iterative, as by applying the same rate we could find that in some strata there are not enough units to increase or to reduce. The function <em>adjustSize</em> permits to obtain the desired final sample size. Let us suppose that the obtained sample size is not affordable. We can reduce it by executing the following code:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">adjustedStrata &lt;-<span class="st"> </span><span class="kw"><a href="../reference/adjustSize.html">adjustSize</a></span>(<span class="dt">size=</span><span class="dv">150</span>,<span class="dt">strata=</span>solution<span class="op">$</span>aggr_strata,<span class="dt">cens=</span><span class="ot">NULL</span>)</a>
<a class="sourceLine" id="cb29-2" data-line-number="2"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb29-3" data-line-number="3"><span class="co">#&gt;  173</span></a>
<a class="sourceLine" id="cb29-4" data-line-number="4"><span class="co">#&gt;  168</span></a>
<a class="sourceLine" id="cb29-5" data-line-number="5"><span class="co">#&gt;  168</span></a>
<a class="sourceLine" id="cb29-6" data-line-number="6"><span class="co">#&gt;  Final adjusted size:  168</span></a>
<a class="sourceLine" id="cb29-7" data-line-number="7"><span class="kw">sum</span>(adjustedStrata<span class="op">$</span>SOLUZ)</a>
<a class="sourceLine" id="cb29-8" data-line-number="8"><span class="co">#&gt; [1] 168</span></a></code></pre></div>
<p>Instead, if we want to increase the size because the budget allows to do this, then this is the code:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1">adjustedStrata &lt;-<span class="st"> </span><span class="kw"><a href="../reference/adjustSize.html">adjustSize</a></span>(<span class="dt">size=</span><span class="dv">250</span>,<span class="dt">strata=</span>solution<span class="op">$</span>aggr_strata,<span class="dt">cens=</span><span class="ot">NULL</span>)</a>
<a class="sourceLine" id="cb30-2" data-line-number="2"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb30-3" data-line-number="3"><span class="co">#&gt;  233</span></a>
<a class="sourceLine" id="cb30-4" data-line-number="4"><span class="co">#&gt;  233</span></a>
<a class="sourceLine" id="cb30-5" data-line-number="5"><span class="co">#&gt;  Final adjusted size:  233</span></a>
<a class="sourceLine" id="cb30-6" data-line-number="6"><span class="kw">sum</span>(adjustedStrata<span class="op">$</span>SOLUZ)</a>
<a class="sourceLine" id="cb30-7" data-line-number="7"><span class="co">#&gt; [1] 233</span></a></code></pre></div>
<p>The difference between the desired sample size and the actual adjusted size depends on the number of strata in the optimized solution. Consider that the adjustment is performed in each stratum by taking into account the relative difference between the current sample size and the desired one: this produces an allocation that is expressed by a real number, that must be rounded. The higher the number of strata, the higher the impact of the rounding in all strata on the final adjusted sample size.</p>
</div>
<div id="analysis-of-results" class="section level1">
<h1 class="hasAnchor">
<a href="#analysis-of-results" class="anchor"></a>Analysis of results</h1>
<p>This function has two purposes:</p>
<ol style="list-style-type: decimal">
<li>instrumental to the processing of the sampling frame (attribution of the labels of the optimized strata to the population units);</li>
<li>analysis of the aggregation of the atomic strata obtained in the optimized solution.</li>
</ol>
<p>The function <em>updateStrata</em> assigns the labels of the new strata to the initial one in the dataframe <em>strata</em>, and produces:</p>
<ul>
<li>a new dataframe named <em>newstrata</em> containing all the information in the <em>strata</em> dataframe, plus the labels of the new optimized strata;</li>
<li>a table, contained in the dataset <em>strata_aggregation.txt</em>, showing in which way each optimized stratum aggregates the auxiliary variables X’s.</li>
</ul>
<p>The function is invoked in this way:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1">newstrata &lt;-<span class="st"> </span><span class="kw"><a href="../reference/updateStrata.html">updateStrata</a></span>(swissstrata, </a>
<a class="sourceLine" id="cb31-2" data-line-number="2">                          solution, </a>
<a class="sourceLine" id="cb31-3" data-line-number="3">                          <span class="dt">writeFiles =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>Now, the atomic strata are associated to the aggregate strata defined in the optimal solution, by means of the variable <em>LABEL</em>. If we want to analyse in detail the new structure of the stratification, we can look at the <em>strata_aggregation.txt</em> file:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1">strata_aggregation &lt;-<span class="st"> </span><span class="kw">read.delim</span>(<span class="st">"strata_aggregation.txt"</span>)</a>
<a class="sourceLine" id="cb32-2" data-line-number="2"><span class="kw">head</span>(strata_aggregation)</a>
<a class="sourceLine" id="cb32-3" data-line-number="3"><span class="co">#&gt;   DOM1 AGGR_STRATUM X1 X2 X3 X4 X5 X6</span></a>
<a class="sourceLine" id="cb32-4" data-line-number="4"><span class="co">#&gt; 1    1            1  1  1  1  1  1  1</span></a>
<a class="sourceLine" id="cb32-5" data-line-number="5"><span class="co">#&gt; 2    1            1  1  1  2  1  1  1</span></a>
<a class="sourceLine" id="cb32-6" data-line-number="6"><span class="co">#&gt; 3    1            1  6  3  2  2  2  1</span></a>
<a class="sourceLine" id="cb32-7" data-line-number="7"><span class="co">#&gt; 4    1            1  7  1  1  1  1  2</span></a>
<a class="sourceLine" id="cb32-8" data-line-number="8"><span class="co">#&gt; 5    1            2  1  1  1  1  1  2</span></a>
<a class="sourceLine" id="cb32-9" data-line-number="9"><span class="co">#&gt; 6    1            3  1  1  1  2  1  1</span></a></code></pre></div>
<p>In this structure, for each aggregate stratum the values of the X’s variables in each contributing atomic stratum are reported. It is then possible to understand the meaning of each aggregate stratum produced by the optimization.</p>
</div>
<div id="updating-the-frame-and-selecting-the-sample" class="section level1">
<h1 class="hasAnchor">
<a href="#updating-the-frame-and-selecting-the-sample" class="anchor"></a>Updating the frame and selecting the sample</h1>
<p>Once the optimal stratification has been obtained, to be operational we need to accomplish the following two steps:</p>
<ul>
<li>to update the frame units with new stratum labels (combination of the new values of the auxiliary variables X’s);</li>
<li>to select the sample from the frame.</li>
</ul>
<p>As for the first, we execute the following command:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1">framenew &lt;-<span class="st"> </span><span class="kw"><a href="../reference/updateFrame.html">updateFrame</a></span>(swissframe, newstrata, <span class="dt">writeFiles=</span><span class="ot">FALSE</span>)</a></code></pre></div>
<p>The function <em>updateFrame</em> receives as arguments the indication of the dataframe in which the frame information is memorised, and of the dataframe produced by the execution of the <em>updateStrata</em> function. The execution of this function produces a dataframe <em>framenew</em>, and also a file (named <em>framenew.txt</em>) with the labels of the new strata produced by the optimisation step. The allocation of units is contained in the <em>SOLUZ</em> column of the dataset <em>outstrata.txt</em>. At this point it is possible to select the sample from the new version of the frame:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1">sample &lt;-<span class="st"> </span><span class="kw"><a href="../reference/selectSample.html">selectSample</a></span>(framenew, solution<span class="op">$</span>aggr_strata, <span class="dt">writeFiles=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb34-2" data-line-number="2"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb34-3" data-line-number="3"><span class="co">#&gt; *** Sample has been drawn successfully ***</span></a>
<a class="sourceLine" id="cb34-4" data-line-number="4"><span class="co">#&gt;  202  units have been selected from  80  strata</span></a>
<a class="sourceLine" id="cb34-5" data-line-number="5"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb34-6" data-line-number="6"><span class="co">#&gt; ==&gt; There have been  13  take-all strata </span></a>
<a class="sourceLine" id="cb34-7" data-line-number="7"><span class="co">#&gt; from which have been selected  27 units</span></a></code></pre></div>
<p>that produces two .csv files:</p>
<ul>
<li>
<em>sample.csv</em> containing the units of the frame that have been selected, together with the weight that has been calculated for each one of them;</li>
<li>
<em>sample.chk.csv</em> containing information on the selection: for each stratum, the number of units in the population, the planned sample, the number of selected units, the sum of their weights that must equalise the number of units in the population.</li>
</ul>
<p>The <em>selectSample</em> operates by drawing a simple random sampling in each stratum.</p>
<p>A variant of this function is <em>selectSampleSystematic</em>. The only difference is in the method used for selecting units in each strata, that is by executing the following steps:</p>
<ol style="list-style-type: decimal">
<li>a selection interval is determined by considering the inverse of the sampling rate in the stratum;</li>
<li>a starting point is determined by selecting a value in this interval;</li>
<li>the selection proceeds by selecting as first unit the one corresponding to the above value, and then selecting all the units individuated by adding the selection interval.</li>
</ol>
<p>This selection method can be useful if associated to a particular ordering of the selection frame, where the ordering variable(s) can be considered as additional stratum variable(s). For instance, we could decide that it could be important to consider the overall population in municipalities when selecting units. Here is the code:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1"><span class="co"># adding POPTOT to framenew</span></a>
<a class="sourceLine" id="cb35-2" data-line-number="2"><span class="kw">data</span>(<span class="st">"swissmunicipalities"</span>)</a>
<a class="sourceLine" id="cb35-3" data-line-number="3">framenew &lt;-<span class="st"> </span><span class="kw">merge</span>(framenew,swissmunicipalities[,<span class="kw">c</span>(<span class="st">"REG"</span>,<span class="st">"Nom"</span>,<span class="st">"POPTOT"</span>)],</a>
<a class="sourceLine" id="cb35-4" data-line-number="4">                  <span class="dt">by.x=</span><span class="kw">c</span>(<span class="st">"REG"</span>,<span class="st">"ID"</span>),<span class="dt">by.y=</span><span class="kw">c</span>(<span class="st">"REG"</span>,<span class="st">"Nom"</span>))</a>
<a class="sourceLine" id="cb35-5" data-line-number="5"><span class="co"># selection of sample with systematic method</span></a>
<a class="sourceLine" id="cb35-6" data-line-number="6">sample &lt;-<span class="st"> </span><span class="kw"><a href="../reference/selectSampleSystematic.html">selectSampleSystematic</a></span>(<span class="dt">frame=</span>framenew,</a>
<a class="sourceLine" id="cb35-7" data-line-number="7">                                 <span class="dt">outstrata=</span>solution<span class="op">$</span>aggr_strata,</a>
<a class="sourceLine" id="cb35-8" data-line-number="8">                                 <span class="dt">sortvariable =</span> <span class="kw">c</span>(<span class="st">"POPTOT"</span>))</a>
<a class="sourceLine" id="cb35-9" data-line-number="9"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb35-10" data-line-number="10"><span class="co">#&gt; *** Sample has been drawn successfully ***</span></a>
<a class="sourceLine" id="cb35-11" data-line-number="11"><span class="co">#&gt;  202  units have been selected from  80  strata</span></a>
<a class="sourceLine" id="cb35-12" data-line-number="12"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb35-13" data-line-number="13"><span class="co">#&gt; ==&gt; There have been  13  take-all strata </span></a>
<a class="sourceLine" id="cb35-14" data-line-number="14"><span class="co">#&gt; from which have been selected  27 units</span></a>
<a class="sourceLine" id="cb35-15" data-line-number="15"><span class="kw">head</span>(sample,<span class="dv">3</span>)</a>
<a class="sourceLine" id="cb35-16" data-line-number="16"><span class="co">#&gt;   DOMAINVALUE STRATO REG          ID     STRATUM PROGR X1 X2 X3 X4 X5 X6</span></a>
<a class="sourceLine" id="cb35-17" data-line-number="17"><span class="co">#&gt; 1           1      1   1      Cuarny 1*1*1*1*1*1  2568  1  1  1  1  1  1</span></a>
<a class="sourceLine" id="cb35-18" data-line-number="18"><span class="co">#&gt; 2           1      1   1 Fontanezier 1*1*1*1*1*1  2806  1  1  1  1  1  1</span></a>
<a class="sourceLine" id="cb35-19" data-line-number="19"><span class="co">#&gt; 3           1      1   1        Riex 1*1*1*1*1*1  2270  1  1  1  1  1  1</span></a>
<a class="sourceLine" id="cb35-20" data-line-number="20"><span class="co">#&gt;   Y1 Y2  Y3 Y4 LABEL POPTOT  WEIGHTS        FPC</span></a>
<a class="sourceLine" id="cb35-21" data-line-number="21"><span class="co">#&gt; 1 49 47  60 15     1    171 65.66667 0.01522843</span></a>
<a class="sourceLine" id="cb35-22" data-line-number="22"><span class="co">#&gt; 2 17 12  24 17     1     70 65.66667 0.01522843</span></a>
<a class="sourceLine" id="cb35-23" data-line-number="23"><span class="co">#&gt; 3 61 83 111 45     1    300 65.66667 0.01522843</span></a></code></pre></div>
</div>
<div id="evaluation-of-the-found-solution" class="section level1">
<h1 class="hasAnchor">
<a href="#evaluation-of-the-found-solution" class="anchor"></a>Evaluation of the found solution</h1>
<p>In order to be confident about the quality of the found solution, the function <em>evalSolution</em> allows to run a simulation, based on the selection of a desired number of samples from the frame to which the stratification, identified as the best, has been applied. The user can invoke this function also indicating the number of samples to be drawn:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" data-line-number="1">eval &lt;-<span class="st"> </span><span class="kw"><a href="../reference/evalSolution.html">evalSolution</a></span>(framenew, </a>
<a class="sourceLine" id="cb36-2" data-line-number="2">                     solution<span class="op">$</span>aggr_strata, </a>
<a class="sourceLine" id="cb36-3" data-line-number="3">                     <span class="dt">nsampl=</span><span class="dv">200</span>, </a>
<a class="sourceLine" id="cb36-4" data-line-number="4">                     <span class="dt">writeFiles=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb36-5" data-line-number="5">                     <span class="dt">progress=</span><span class="ot">FALSE</span>) </a></code></pre></div>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-29-1.png" width="700"><img src="SamplingStrata_files/figure-html/unnamed-chunk-29-2.png" width="700"></p>
<p>For each drawn sample, the estimates related to the Y’s are calculated. Their mean and standard deviation are also computed, in order to produce the CV related to each variable in every domain. These CV’s can be inspected and compared to the constraints:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1">eval<span class="op">$</span>coeff_var</a>
<a class="sourceLine" id="cb37-2" data-line-number="2"><span class="co">#&gt;          CV1        CV2        CV3        CV4  dom</span></a>
<a class="sourceLine" id="cb37-3" data-line-number="3"><span class="co">#&gt; 1 0.07147474 0.06725882 0.06631338 0.07693790 DOM1</span></a>
<a class="sourceLine" id="cb37-4" data-line-number="4"><span class="co">#&gt; 2 0.07629785 0.07768588 0.07965343 0.08727034 DOM2</span></a>
<a class="sourceLine" id="cb37-5" data-line-number="5"><span class="co">#&gt; 3 0.09011818 0.08499232 0.08551833 0.10838697 DOM3</span></a>
<a class="sourceLine" id="cb37-6" data-line-number="6"><span class="co">#&gt; 4 0.08096880 0.07995800 0.08632999 0.10023420 DOM4</span></a>
<a class="sourceLine" id="cb37-7" data-line-number="7"><span class="co">#&gt; 5 0.07712814 0.07851861 0.07605702 0.08179382 DOM5</span></a>
<a class="sourceLine" id="cb37-8" data-line-number="8"><span class="co">#&gt; 6 0.07405498 0.07989413 0.07908099 0.09841308 DOM6</span></a>
<a class="sourceLine" id="cb37-9" data-line-number="9"><span class="co">#&gt; 7 0.08201231 0.08307746 0.07756346 0.08839971 DOM7</span></a>
<a class="sourceLine" id="cb37-10" data-line-number="10">swisserrors</a>
<a class="sourceLine" id="cb37-11" data-line-number="11"><span class="co">#&gt;    DOM  CV1  CV2  CV3  CV4 domainvalue</span></a>
<a class="sourceLine" id="cb37-12" data-line-number="12"><span class="co">#&gt; 1 DOM1 0.08 0.12 0.08 0.12           1</span></a>
<a class="sourceLine" id="cb37-13" data-line-number="13"><span class="co">#&gt; 2 DOM1 0.08 0.12 0.08 0.12           2</span></a>
<a class="sourceLine" id="cb37-14" data-line-number="14"><span class="co">#&gt; 3 DOM1 0.08 0.12 0.08 0.12           3</span></a>
<a class="sourceLine" id="cb37-15" data-line-number="15"><span class="co">#&gt; 4 DOM1 0.08 0.12 0.08 0.12           4</span></a>
<a class="sourceLine" id="cb37-16" data-line-number="16"><span class="co">#&gt; 5 DOM1 0.08 0.12 0.08 0.12           5</span></a>
<a class="sourceLine" id="cb37-17" data-line-number="17"><span class="co">#&gt; 6 DOM1 0.08 0.12 0.08 0.12           6</span></a>
<a class="sourceLine" id="cb37-18" data-line-number="18"><span class="co">#&gt; 7 DOM1 0.08 0.12 0.08 0.12           7</span></a></code></pre></div>
<p>Whenever the precision constraints are not strictly observed, then it is possible to carry out the rounding to the upper integer (<em>ceiling</em>) the allocation vector. Accordingly to the Bethel algorithm, this ensure compliance to the precision constraints.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="kw">sum</span>(solution<span class="op">$</span>aggr_strata<span class="op">$</span>SOLUZ)</a>
<a class="sourceLine" id="cb38-2" data-line-number="2"><span class="co">#&gt; [1] 201.4153</span></a>
<a class="sourceLine" id="cb38-3" data-line-number="3">outstrata &lt;-<span class="st"> </span>solution<span class="op">$</span>aggr_strata</a>
<a class="sourceLine" id="cb38-4" data-line-number="4">outstrata<span class="op">$</span>SOLUZ &lt;-<span class="st"> </span><span class="kw">ceiling</span>(outstrata<span class="op">$</span>SOLUZ)</a>
<a class="sourceLine" id="cb38-5" data-line-number="5"><span class="kw">sum</span>(outstrata<span class="op">$</span>SOLUZ)</a>
<a class="sourceLine" id="cb38-6" data-line-number="6"><span class="co">#&gt; [1] 224</span></a>
<a class="sourceLine" id="cb38-7" data-line-number="7">eval_ceiling &lt;-<span class="st"> </span><span class="kw"><a href="../reference/evalSolution.html">evalSolution</a></span>(framenew, </a>
<a class="sourceLine" id="cb38-8" data-line-number="8">                     outstrata, </a>
<a class="sourceLine" id="cb38-9" data-line-number="9">                     <span class="dt">nsampl=</span><span class="dv">200</span>,</a>
<a class="sourceLine" id="cb38-10" data-line-number="10">                     <span class="dt">writeFiles =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb38-11" data-line-number="11">                     <span class="dt">progress =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-31-1.png" width="700"><img src="SamplingStrata_files/figure-html/unnamed-chunk-31-2.png" width="700"></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1">eval_ceiling<span class="op">$</span>coeff_var</a>
<a class="sourceLine" id="cb39-2" data-line-number="2"><span class="co">#&gt;          CV1        CV2        CV3        CV4  dom</span></a>
<a class="sourceLine" id="cb39-3" data-line-number="3"><span class="co">#&gt; 1 0.06761089 0.06294727 0.06250508 0.06172660 DOM1</span></a>
<a class="sourceLine" id="cb39-4" data-line-number="4"><span class="co">#&gt; 2 0.07749539 0.07972889 0.08029889 0.09188396 DOM2</span></a>
<a class="sourceLine" id="cb39-5" data-line-number="5"><span class="co">#&gt; 3 0.07193124 0.07024715 0.07063314 0.08375254 DOM3</span></a>
<a class="sourceLine" id="cb39-6" data-line-number="6"><span class="co">#&gt; 4 0.06428027 0.06524182 0.06752265 0.07525093 DOM4</span></a>
<a class="sourceLine" id="cb39-7" data-line-number="7"><span class="co">#&gt; 5 0.07105180 0.07342614 0.07015221 0.07424819 DOM5</span></a>
<a class="sourceLine" id="cb39-8" data-line-number="8"><span class="co">#&gt; 6 0.07803050 0.07754854 0.07942112 0.07788182 DOM6</span></a>
<a class="sourceLine" id="cb39-9" data-line-number="9"><span class="co">#&gt; 7 0.07410521 0.07390974 0.07261680 0.09126325 DOM7</span></a>
<a class="sourceLine" id="cb39-10" data-line-number="10">swisserrors</a>
<a class="sourceLine" id="cb39-11" data-line-number="11"><span class="co">#&gt;    DOM  CV1  CV2  CV3  CV4 domainvalue</span></a>
<a class="sourceLine" id="cb39-12" data-line-number="12"><span class="co">#&gt; 1 DOM1 0.08 0.12 0.08 0.12           1</span></a>
<a class="sourceLine" id="cb39-13" data-line-number="13"><span class="co">#&gt; 2 DOM1 0.08 0.12 0.08 0.12           2</span></a>
<a class="sourceLine" id="cb39-14" data-line-number="14"><span class="co">#&gt; 3 DOM1 0.08 0.12 0.08 0.12           3</span></a>
<a class="sourceLine" id="cb39-15" data-line-number="15"><span class="co">#&gt; 4 DOM1 0.08 0.12 0.08 0.12           4</span></a>
<a class="sourceLine" id="cb39-16" data-line-number="16"><span class="co">#&gt; 5 DOM1 0.08 0.12 0.08 0.12           5</span></a>
<a class="sourceLine" id="cb39-17" data-line-number="17"><span class="co">#&gt; 6 DOM1 0.08 0.12 0.08 0.12           6</span></a>
<a class="sourceLine" id="cb39-18" data-line-number="18"><span class="co">#&gt; 7 DOM1 0.08 0.12 0.08 0.12           7</span></a></code></pre></div>
<p>These values are on average compliant with the precision constraints set.</p>
</div>
<div id="handling-take-all-strata-in-the-optimization-step" class="section level1">
<h1 class="hasAnchor">
<a href="#handling-take-all-strata-in-the-optimization-step" class="anchor"></a>Handling ‘take-all’ strata in the optimization step</h1>
<p>As input to the optimization step, together with proper sampling strata, it is also possible to provide <em>take-all</em> strata. These strata will not be subject to optimisation as the proper strata, but they will contribute to the determination of the best stratification, as their presence in a given domain will permit to satisfy precision constraint with a lower number of units belonging to proper sampling strata.</p>
<p>In order to correctly execute the optimization and further steps, it is necessary to perform a pre-processing of the overall input. The first step to be executed consists in the bi-partition of units to be censused and of units to be sampled, in order to build two different frames. As an example, we take the units with the highest values of the auxiliary variables as the ones to be selected in any case:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1"><span class="kw">data</span>(swisserrors)</a>
<a class="sourceLine" id="cb40-2" data-line-number="2"><span class="kw">data</span>(swissstrata)</a>
<a class="sourceLine" id="cb40-3" data-line-number="3"><span class="kw">data</span>(swissframe)</a>
<a class="sourceLine" id="cb40-4" data-line-number="4"><span class="co">#----Selection of units to be censused from the frame</span></a>
<a class="sourceLine" id="cb40-5" data-line-number="5">ind_framecens &lt;-<span class="st"> </span><span class="kw">which</span>(swissframe<span class="op">$</span>X1 <span class="op">&gt;</span><span class="st"> </span><span class="dv">12</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb40-6" data-line-number="6"><span class="st">                       </span>swissframe<span class="op">$</span>X2 <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span> <span class="op">|</span><span class="st"> </span></a>
<a class="sourceLine" id="cb40-7" data-line-number="7"><span class="st">                       </span>swissframe<span class="op">$</span>X3 <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb40-8" data-line-number="8"><span class="st">                       </span>swissframe<span class="op">$</span>X4 <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span> <span class="op">|</span></a>
<a class="sourceLine" id="cb40-9" data-line-number="9"><span class="st">                       </span>swissframe<span class="op">$</span>X5 <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span> <span class="op">|</span><span class="st"> </span></a>
<a class="sourceLine" id="cb40-10" data-line-number="10"><span class="st">                       </span>swissframe<span class="op">$</span>X6 <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span> )</a>
<a class="sourceLine" id="cb40-11" data-line-number="11">framecens &lt;-<span class="st"> </span>swissframe[ind_framecens,]</a>
<a class="sourceLine" id="cb40-12" data-line-number="12"><span class="kw">nrow</span>(framecens)</a>
<a class="sourceLine" id="cb40-13" data-line-number="13"><span class="co">#&gt; [1] 302</span></a>
<a class="sourceLine" id="cb40-14" data-line-number="14"><span class="co">#----Selection of units to be sampled from the frame</span></a>
<a class="sourceLine" id="cb40-15" data-line-number="15"><span class="co"># (complement to the previous)</span></a>
<a class="sourceLine" id="cb40-16" data-line-number="16">framesamp &lt;-<span class="st"> </span>swissframe[<span class="op">-</span>ind_framecens,]</a>
<a class="sourceLine" id="cb40-17" data-line-number="17"><span class="kw">nrow</span>(framesamp)</a>
<a class="sourceLine" id="cb40-18" data-line-number="18"><span class="co">#&gt; [1] 2594</span></a></code></pre></div>
<p>In this way, we have included all units to be surely selected in ‘framecens’, and the remaining in ‘framesamp’. At the end of the process, the sample will be selected only from ‘framesamp’, while the units in ‘framecens’ will be simply added to the sample.</p>
<p>We can obtain census strata and sampling strata by applying <em>buildStrataDF</em> respectively to <em>framecens</em> and <em>framesamp</em>:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1"><span class="co"># Build strata to be censused and sampled</span></a>
<a class="sourceLine" id="cb41-2" data-line-number="2">cens &lt;-<span class="st"> </span><span class="kw"><a href="../reference/buildStrataDF.html">buildStrataDF</a></span>(framecens,<span class="dt">progress =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb41-3" data-line-number="3"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb41-4" data-line-number="4"><span class="co">#&gt; Computations are being done on population data</span></a>
<a class="sourceLine" id="cb41-5" data-line-number="5"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb41-6" data-line-number="6"><span class="co">#&gt; Number of strata:  231</span></a>
<a class="sourceLine" id="cb41-7" data-line-number="7"><span class="co">#&gt; ... of which with only one unit:  187</span></a>
<a class="sourceLine" id="cb41-8" data-line-number="8"><span class="kw">sum</span>(cens<span class="op">$</span>N)</a>
<a class="sourceLine" id="cb41-9" data-line-number="9"><span class="co">#&gt; [1] 302</span></a>
<a class="sourceLine" id="cb41-10" data-line-number="10">strata &lt;-<span class="st"> </span><span class="kw"><a href="../reference/buildStrataDF.html">buildStrataDF</a></span>(framesamp,<span class="dt">progress =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb41-11" data-line-number="11"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb41-12" data-line-number="12"><span class="co">#&gt; Computations are being done on population data</span></a>
<a class="sourceLine" id="cb41-13" data-line-number="13"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb41-14" data-line-number="14"><span class="co">#&gt; Number of strata:  410</span></a>
<a class="sourceLine" id="cb41-15" data-line-number="15"><span class="co">#&gt; ... of which with only one unit:  202</span></a>
<a class="sourceLine" id="cb41-16" data-line-number="16"><span class="kw">sum</span>(strata<span class="op">$</span>N)</a>
<a class="sourceLine" id="cb41-17" data-line-number="17"><span class="co">#&gt; [1] 2594</span></a></code></pre></div>
<p>and</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1"><span class="kw">sum</span>(cens<span class="op">$</span>N)</a>
<a class="sourceLine" id="cb42-2" data-line-number="2"><span class="co">#&gt; [1] 302</span></a>
<a class="sourceLine" id="cb42-3" data-line-number="3"><span class="kw">sum</span>(strata<span class="op">$</span>N)</a>
<a class="sourceLine" id="cb42-4" data-line-number="4"><span class="co">#&gt; [1] 2594</span></a></code></pre></div>
<p>Now we have all required inputs to run ‘optimizeStrata’ in presence of the ‘take-all’ strata:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1">solution &lt;-<span class="st"> </span><span class="kw"><a href="../reference/optimizeStrata.html">optimizeStrata</a></span>(</a>
<a class="sourceLine" id="cb43-2" data-line-number="2">    <span class="dt">errors =</span> swisserrors, </a>
<a class="sourceLine" id="cb43-3" data-line-number="3">    <span class="dt">strata =</span> strata, </a>
<a class="sourceLine" id="cb43-4" data-line-number="4">    <span class="dt">cens =</span> cens, </a>
<a class="sourceLine" id="cb43-5" data-line-number="5">    <span class="dt">strcens =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb43-6" data-line-number="6">    <span class="dt">parallel =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb43-7" data-line-number="7">    <span class="dt">writeFiles =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb43-8" data-line-number="8">    <span class="dt">showPlot =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb43-9" data-line-number="9">)</a>
<a class="sourceLine" id="cb43-10" data-line-number="10"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb43-11" data-line-number="11"><span class="co">#&gt;  *** Domain :  1   1</span></a>
<a class="sourceLine" id="cb43-12" data-line-number="12"><span class="co">#&gt;  Number of strata :  79</span></a>
<a class="sourceLine" id="cb43-13" data-line-number="13"><span class="co">#&gt; GA Settings</span></a>
<a class="sourceLine" id="cb43-14" data-line-number="14"><span class="co">#&gt;   Population size       = 20</span></a>
<a class="sourceLine" id="cb43-15" data-line-number="15"><span class="co">#&gt;   Number of Generations = 50</span></a>
<a class="sourceLine" id="cb43-16" data-line-number="16"><span class="co">#&gt;   Elitism               = 4</span></a>
<a class="sourceLine" id="cb43-17" data-line-number="17"><span class="co">#&gt;   Mutation Chance       = 0.0125</span></a></code></pre></div>
<p>Once the optimized solution has been produced, the next steps are executed by considering only the sampling part of the frame:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1">newstrata &lt;-<span class="st"> </span><span class="kw"><a href="../reference/updateStrata.html">updateStrata</a></span>(strata, solution)</a>
<a class="sourceLine" id="cb44-2" data-line-number="2"><span class="co"># updating sampling frame with new strata labels</span></a>
<a class="sourceLine" id="cb44-3" data-line-number="3">framenew &lt;-<span class="st"> </span><span class="kw"><a href="../reference/updateFrame.html">updateFrame</a></span>(<span class="dt">frame=</span>framesamp,<span class="dt">newstrata=</span>newstrata)</a>
<a class="sourceLine" id="cb44-4" data-line-number="4"><span class="co"># selection of sample from sampling strata</span></a>
<a class="sourceLine" id="cb44-5" data-line-number="5">sample &lt;-<span class="st"> </span><span class="kw"><a href="../reference/selectSample.html">selectSample</a></span>(<span class="dt">frame=</span>framenew,<span class="dt">outstrata=</span>solution<span class="op">$</span>aggr_strata)</a>
<a class="sourceLine" id="cb44-6" data-line-number="6"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb44-7" data-line-number="7"><span class="co">#&gt; *** Sample has been drawn successfully ***</span></a>
<a class="sourceLine" id="cb44-8" data-line-number="8"><span class="co">#&gt;  119  units have been selected from  45  strata</span></a></code></pre></div>
<p>Finally, the units in the ‘take-all’ strata can be added to sampled ones. First, the census frame needs to be made homogeneous to the sample frame in order to permit the ‘rbind’ step:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1"><span class="co"># addition of necessary variables to </span></a>
<a class="sourceLine" id="cb45-2" data-line-number="2"><span class="kw">colnames</span>(framesamp) &lt;-<span class="st"> </span><span class="kw">toupper</span>(<span class="kw">colnames</span>(framesamp))</a>
<a class="sourceLine" id="cb45-3" data-line-number="3"><span class="kw">colnames</span>(framecens) &lt;-<span class="st"> </span><span class="kw">toupper</span>(<span class="kw">colnames</span>(framecens))</a>
<a class="sourceLine" id="cb45-4" data-line-number="4">framecens<span class="op">$</span>WEIGHTS &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span>,<span class="kw">nrow</span>(framecens))</a>
<a class="sourceLine" id="cb45-5" data-line-number="5">framecens<span class="op">$</span>FPC &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span>,<span class="kw">nrow</span>(framecens))</a>
<a class="sourceLine" id="cb45-6" data-line-number="6">framecens<span class="op">$</span>LABEL &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="st">"999999"</span>,<span class="kw">nrow</span>(framecens))</a>
<a class="sourceLine" id="cb45-7" data-line-number="7">framecens<span class="op">$</span>STRATUM &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="st">"999999"</span>,<span class="kw">nrow</span>(framecens))</a>
<a class="sourceLine" id="cb45-8" data-line-number="8">framecens<span class="op">$</span>STRATO &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="st">"999999"</span>,<span class="kw">nrow</span>(framecens))</a></code></pre></div>
<p>The overall set of units to be surveyed is obtainable in this way:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1">survey &lt;-<span class="st"> </span><span class="kw">rbind</span>(sample,framecens)</a></code></pre></div>
<p>and this is the proportion of sampling and censused units:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1">survey<span class="op">$</span>cens &lt;-<span class="st"> </span><span class="kw">ifelse</span>(survey<span class="op">$</span>LABEL <span class="op">==</span><span class="st"> "999999"</span>,<span class="dv">1</span>,<span class="dv">0</span>)</a>
<a class="sourceLine" id="cb47-2" data-line-number="2"><span class="kw">table</span>(survey<span class="op">$</span>cens)</a>
<a class="sourceLine" id="cb47-3" data-line-number="3"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb47-4" data-line-number="4"><span class="co">#&gt;   0   1 </span></a>
<a class="sourceLine" id="cb47-5" data-line-number="5"><span class="co">#&gt; 119 302</span></a></code></pre></div>
<p>In order to verify compliance to the precision constraint, we perform the following:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1">cens2 &lt;-<span class="st"> </span>cens[,<span class="op">-</span><span class="kw">c</span>(<span class="dv">14</span><span class="op">:</span><span class="dv">19</span>)]</a>
<a class="sourceLine" id="cb48-2" data-line-number="2">cens2<span class="op">$</span>SOLUZ &lt;-<span class="st"> </span>cens2<span class="op">$</span>N</a>
<a class="sourceLine" id="cb48-3" data-line-number="3">stratatot &lt;-<span class="st"> </span><span class="kw">rbind</span>(solution<span class="op">$</span>aggr_strata,cens2)</a>
<a class="sourceLine" id="cb48-4" data-line-number="4"><span class="kw"><a href="../reference/expected_CV.html">expected_CV</a></span>(stratatot)</a>
<a class="sourceLine" id="cb48-5" data-line-number="5"><span class="co">#&gt;      cv(Y1) cv(Y2) cv(Y3) cv(Y4)</span></a>
<a class="sourceLine" id="cb48-6" data-line-number="6"><span class="co">#&gt; DOM1  0.076  0.067  0.075  0.076</span></a>
<a class="sourceLine" id="cb48-7" data-line-number="7"><span class="co">#&gt; DOM2  0.072  0.071  0.075  0.080</span></a>
<a class="sourceLine" id="cb48-8" data-line-number="8"><span class="co">#&gt; DOM3  0.074  0.074  0.069  0.070</span></a>
<a class="sourceLine" id="cb48-9" data-line-number="9"><span class="co">#&gt; DOM4  0.078  0.070  0.079  0.087</span></a>
<a class="sourceLine" id="cb48-10" data-line-number="10"><span class="co">#&gt; DOM5  0.076  0.076  0.077  0.072</span></a>
<a class="sourceLine" id="cb48-11" data-line-number="11"><span class="co">#&gt; DOM6  0.077  0.076  0.080  0.081</span></a>
<a class="sourceLine" id="cb48-12" data-line-number="12"><span class="co">#&gt; DOM7  0.078  0.080  0.077  0.083</span></a></code></pre></div>
</div>
<div id="handling-anticipated-variance" class="section level1">
<h1 class="hasAnchor">
<a href="#handling-anticipated-variance" class="anchor"></a>Handling Anticipated Variance</h1>
<p>In the previous sections it has been assumed that, when optimizing the stratification of a sampling frame, values of the target variables Y’s are available for the generality of the units in the frame, or at least for a sample of them by means of which it is possible to estimate means and standard deviation of Y’s in atomic strata. Of course, this assumption is seldom expected to hold. The situation in which some proxy variables are available in the frame is much more likely to happen. In these situations, instead of directly indicating the real target variables, proxy ones are named as Y’s. By so doing, there is no guarantee that the final stratification and allocation can ensure the compliance to the set of precision constraints.<br>
In order to take into account this problem, and to limit the risk of overestimating the expected precision levels of the optimized solution, it is possible to carry out the optimization by considering, instead of the expected coefficients of variation related to proxy variables, the anticipated coefficients of variation (ACV) that depend on the model that is possile to fit on couples of real target variables and proxy ones. In the current implementation, only models linking continuous variables can be considered. The definition and the use of these models is the same that has been implemented in the package <em>stratification</em> <span class="citation">(see Baillargeon and Rivest 2014)</span>. In particular, the reference here is to two different models, the linear model with heteroscedasticity:</p>
<p><span class="math display">\[Y=beta\times X + epsilon\]</span></p>
<p>where</p>
<p><span class="math display">\[epsilon \sim N(0,sig2 X^{gamma})\]</span></p>
<p>(in case gamma = 0, then the model is homoscedastic)</p>
<p>and the loglinear model:</p>
<p><span class="math display">\[Y= \exp (beta \times log(X) + epsilon)\]</span></p>
<p>where</p>
<p><span class="math display">\[epsilon \sim N(0,sig2)\]</span></p>
<p>In order to make evident the importance of the above, consider the following example, based on the dataset <em>nations</em> available in the package.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1"><span class="kw">data</span>(nations)</a>
<a class="sourceLine" id="cb49-2" data-line-number="2"><span class="kw">head</span>(nations)</a>
<a class="sourceLine" id="cb49-3" data-line-number="3"><span class="co">#&gt;          Country  TFR contraception infant.mortality   GDP  region</span></a>
<a class="sourceLine" id="cb49-4" data-line-number="4"><span class="co">#&gt; 1    Afghanistan 6.90            63              154  2848    Asia</span></a>
<a class="sourceLine" id="cb49-5" data-line-number="5"><span class="co">#&gt; 2        Albania 2.60            47               32   863  Europe</span></a>
<a class="sourceLine" id="cb49-6" data-line-number="6"><span class="co">#&gt; 3        Algeria 3.81            52               44  1531  Africa</span></a>
<a class="sourceLine" id="cb49-7" data-line-number="7"><span class="co">#&gt; 4 American-Samoa 1.35            71               11  2433 Oceania</span></a>
<a class="sourceLine" id="cb49-8" data-line-number="8"><span class="co">#&gt; 5        Andorra 1.61            71                7 19121  Europe</span></a>
<a class="sourceLine" id="cb49-9" data-line-number="9"><span class="co">#&gt; 6         Angola 6.69            19              124   355  Africa</span></a>
<a class="sourceLine" id="cb49-10" data-line-number="10"><span class="co">#&gt;   Continent</span></a>
<a class="sourceLine" id="cb49-11" data-line-number="11"><span class="co">#&gt; 1         2</span></a>
<a class="sourceLine" id="cb49-12" data-line-number="12"><span class="co">#&gt; 2         1</span></a>
<a class="sourceLine" id="cb49-13" data-line-number="13"><span class="co">#&gt; 3         4</span></a>
<a class="sourceLine" id="cb49-14" data-line-number="14"><span class="co">#&gt; 4         5</span></a>
<a class="sourceLine" id="cb49-15" data-line-number="15"><span class="co">#&gt; 5         1</span></a>
<a class="sourceLine" id="cb49-16" data-line-number="16"><span class="co">#&gt; 6         4</span></a></code></pre></div>
<p>Let us assume that in the sampling frame only variable <em>GDP</em> (Gross Domestic Product) is available for all countries, while <em>contraception rates</em> and <em>infant mortality rates</em> are available only on a subset of countries (about one third).</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb50-2" data-line-number="2">nations_sample &lt;-<span class="st"> </span>nations[<span class="kw">sample</span>(<span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">207</span>),<span class="dv">70</span>),]</a></code></pre></div>
<p>In this subset we can fit models between GDP and the two variables that we assume are the target of our survey.</p>
<p>One model for <em>infant mortality</em> and <em>GDP</em>:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1">mod_logGDP_INFMORT &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">log</span>(nations_sample<span class="op">$</span>infant.mortality) <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(nations_sample<span class="op">$</span>GDP))</a>
<a class="sourceLine" id="cb51-2" data-line-number="2"><span class="kw">summary</span>(mod_logGDP_INFMORT)</a>
<a class="sourceLine" id="cb51-3" data-line-number="3"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb51-4" data-line-number="4"><span class="co">#&gt; Call:</span></a>
<a class="sourceLine" id="cb51-5" data-line-number="5"><span class="co">#&gt; lm(formula = log(nations_sample$infant.mortality) ~ log(nations_sample$GDP))</span></a>
<a class="sourceLine" id="cb51-6" data-line-number="6"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb51-7" data-line-number="7"><span class="co">#&gt; Residuals:</span></a>
<a class="sourceLine" id="cb51-8" data-line-number="8"><span class="co">#&gt;     Min      1Q  Median      3Q     Max </span></a>
<a class="sourceLine" id="cb51-9" data-line-number="9"><span class="co">#&gt; -1.1292 -0.3765 -0.1455  0.3316  2.6345 </span></a>
<a class="sourceLine" id="cb51-10" data-line-number="10"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb51-11" data-line-number="11"><span class="co">#&gt; Coefficients:</span></a>
<a class="sourceLine" id="cb51-12" data-line-number="12"><span class="co">#&gt;                         Estimate Std. Error t value             Pr(&gt;|t|)</span></a>
<a class="sourceLine" id="cb51-13" data-line-number="13"><span class="co">#&gt; (Intercept)              6.86295    0.33620   20.41 &lt; 0.0000000000000002</span></a>
<a class="sourceLine" id="cb51-14" data-line-number="14"><span class="co">#&gt; log(nations_sample$GDP) -0.46580    0.04389  -10.61 0.000000000000000452</span></a>
<a class="sourceLine" id="cb51-15" data-line-number="15"><span class="co">#&gt;                            </span></a>
<a class="sourceLine" id="cb51-16" data-line-number="16"><span class="co">#&gt; (Intercept)             ***</span></a>
<a class="sourceLine" id="cb51-17" data-line-number="17"><span class="co">#&gt; log(nations_sample$GDP) ***</span></a>
<a class="sourceLine" id="cb51-18" data-line-number="18"><span class="co">#&gt; ---</span></a>
<a class="sourceLine" id="cb51-19" data-line-number="19"><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></a>
<a class="sourceLine" id="cb51-20" data-line-number="20"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb51-21" data-line-number="21"><span class="co">#&gt; Residual standard error: 0.6158 on 68 degrees of freedom</span></a>
<a class="sourceLine" id="cb51-22" data-line-number="22"><span class="co">#&gt; Multiple R-squared:  0.6236, Adjusted R-squared:  0.6181 </span></a>
<a class="sourceLine" id="cb51-23" data-line-number="23"><span class="co">#&gt; F-statistic: 112.7 on 1 and 68 DF,  p-value: 0.0000000000000004523</span></a></code></pre></div>
<p>and one model for <em>contraception</em> and <em>GDP</em>:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1">mod_logGDP_CONTRA &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">log</span>(nations_sample<span class="op">$</span>contraception) <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(nations_sample<span class="op">$</span>GDP))</a>
<a class="sourceLine" id="cb52-2" data-line-number="2"><span class="kw">summary</span>(mod_logGDP_CONTRA)</a>
<a class="sourceLine" id="cb52-3" data-line-number="3"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb52-4" data-line-number="4"><span class="co">#&gt; Call:</span></a>
<a class="sourceLine" id="cb52-5" data-line-number="5"><span class="co">#&gt; lm(formula = log(nations_sample$contraception) ~ log(nations_sample$GDP))</span></a>
<a class="sourceLine" id="cb52-6" data-line-number="6"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb52-7" data-line-number="7"><span class="co">#&gt; Residuals:</span></a>
<a class="sourceLine" id="cb52-8" data-line-number="8"><span class="co">#&gt;      Min       1Q   Median       3Q      Max </span></a>
<a class="sourceLine" id="cb52-9" data-line-number="9"><span class="co">#&gt; -1.96139 -0.27360 -0.01435  0.45058  1.25143 </span></a>
<a class="sourceLine" id="cb52-10" data-line-number="10"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb52-11" data-line-number="11"><span class="co">#&gt; Coefficients:</span></a>
<a class="sourceLine" id="cb52-12" data-line-number="12"><span class="co">#&gt;                         Estimate Std. Error t value         Pr(&gt;|t|)    </span></a>
<a class="sourceLine" id="cb52-13" data-line-number="13"><span class="co">#&gt; (Intercept)              0.98318    0.30538   3.220          0.00197 ** </span></a>
<a class="sourceLine" id="cb52-14" data-line-number="14"><span class="co">#&gt; log(nations_sample$GDP)  0.34649    0.03986   8.692 0.00000000000122 ***</span></a>
<a class="sourceLine" id="cb52-15" data-line-number="15"><span class="co">#&gt; ---</span></a>
<a class="sourceLine" id="cb52-16" data-line-number="16"><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></a>
<a class="sourceLine" id="cb52-17" data-line-number="17"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb52-18" data-line-number="18"><span class="co">#&gt; Residual standard error: 0.5593 on 68 degrees of freedom</span></a>
<a class="sourceLine" id="cb52-19" data-line-number="19"><span class="co">#&gt; Multiple R-squared:  0.5263, Adjusted R-squared:  0.5193 </span></a>
<a class="sourceLine" id="cb52-20" data-line-number="20"><span class="co">#&gt; F-statistic: 75.55 on 1 and 68 DF,  p-value: 0.000000000001217</span></a></code></pre></div>
<p>We define the <em>sampling frame</em> in this way:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1">nations<span class="op">$</span>progr &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(nations))</a>
<a class="sourceLine" id="cb53-2" data-line-number="2">nations<span class="op">$</span>dom &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb53-3" data-line-number="3">frame &lt;-<span class="st"> </span><span class="kw"><a href="../reference/buildFrameDF.html">buildFrameDF</a></span>(nations,</a>
<a class="sourceLine" id="cb53-4" data-line-number="4">                      <span class="dt">id=</span><span class="st">"Country"</span>,</a>
<a class="sourceLine" id="cb53-5" data-line-number="5">                      <span class="dt">X=</span><span class="st">"progr"</span>,</a>
<a class="sourceLine" id="cb53-6" data-line-number="6">                      <span class="dt">Y=</span><span class="kw">c</span>(<span class="st">"GDP"</span>,<span class="st">"GDP"</span>),</a>
<a class="sourceLine" id="cb53-7" data-line-number="7">                      <span class="dt">domainvalue =</span> <span class="st">"dom"</span>)</a></code></pre></div>
<p>that is, we replicate twice the variable <em>GDP</em> because it will be used once for <em>infant mortality</em> and once for <em>contraception</em>.</p>
<p>We set 10% and 5% precision constraints on these two variables:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1">cv &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">list</span>(<span class="dt">DOM=</span><span class="kw">rep</span>(<span class="st">"DOM1"</span>,<span class="dv">1</span>),</a>
<a class="sourceLine" id="cb54-2" data-line-number="2">                         <span class="dt">CV1=</span><span class="kw">rep</span>(<span class="fl">0.10</span>,<span class="dv">1</span>),</a>
<a class="sourceLine" id="cb54-3" data-line-number="3">                         <span class="dt">CV2=</span><span class="kw">rep</span>(<span class="fl">0.05</span>,<span class="dv">1</span>),</a>
<a class="sourceLine" id="cb54-4" data-line-number="4">                         <span class="dt">domainvalue=</span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb54-5" data-line-number="5">                    ))</a>
<a class="sourceLine" id="cb54-6" data-line-number="6">cv</a>
<a class="sourceLine" id="cb54-7" data-line-number="7"><span class="co">#&gt;    DOM CV1  CV2 domainvalue</span></a>
<a class="sourceLine" id="cb54-8" data-line-number="8"><span class="co">#&gt; 1 DOM1 0.1 0.05           1</span></a></code></pre></div>
<p>We build the strata without any assumption on the variability of the two target variables, and proceed in the optimization:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" data-line-number="1">strata1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/buildStrataDF.html">buildStrataDF</a></span>(frame, <span class="dt">progress =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb55-2" data-line-number="2"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb55-3" data-line-number="3"><span class="co">#&gt; Computations are being done on population data</span></a>
<a class="sourceLine" id="cb55-4" data-line-number="4"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb55-5" data-line-number="5"><span class="co">#&gt; Number of strata:  207</span></a>
<a class="sourceLine" id="cb55-6" data-line-number="6"><span class="co">#&gt; ... of which with only one unit:  207</span></a>
<a class="sourceLine" id="cb55-7" data-line-number="7">solution1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/optimizeStrata.html">optimizeStrata</a></span>(cv,</a>
<a class="sourceLine" id="cb55-8" data-line-number="8">                           strata1,</a>
<a class="sourceLine" id="cb55-9" data-line-number="9">                           <span class="dt">iter =</span> <span class="dv">50</span>,</a>
<a class="sourceLine" id="cb55-10" data-line-number="10">                           <span class="dt">pops =</span> <span class="dv">20</span>,</a>
<a class="sourceLine" id="cb55-11" data-line-number="11">                           <span class="dt">parallel =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb55-12" data-line-number="12">                           <span class="dt">suggestions =</span> <span class="kw"><a href="../reference/KmeansSolution.html">KmeansSolution</a></span>(strata1,cv),</a>
<a class="sourceLine" id="cb55-13" data-line-number="13">                           <span class="dt">writeFiles =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb55-14" data-line-number="14">                           <span class="dt">showPlot =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-47-1.png" width="700"></p>
<pre><code>#&gt; 
#&gt; -----------------
#&gt;  Kmeans solution 
#&gt; -----------------
#&gt;  *** Domain:  1  ***
#&gt;  Number of strata:  7
#&gt;  Sample size     :  17
#&gt;  *** Domain :  1   1
#&gt;  Number of strata :  207
#&gt; ---------------------------------------------
#&gt; Optimal stratification with Genetic Algorithm
#&gt; ---------------------------------------------
#&gt;  *** Parameters ***
#&gt; ---------------------------
#&gt; Domain:  1
#&gt; Maximum number of strata:  207
#&gt; Minimum number of units per stratum:  2
#&gt; Take-all strata (TRUE/FALSE):  FALSE
#&gt; number of sampling strata :  207
#&gt; Number of target variables:  2
#&gt; Number of domains:  1
#&gt; Number of GA iterations:  50
#&gt; Dimension of GA population:  20
#&gt; Mutation chance in GA generation:  NA
#&gt; Elitism rate in GA generation:  0.2
#&gt; Chance to add strata to maximum:  0
#&gt; Allocation with real numbers instead of integers:  TRUE
#&gt; Suggestion:  5 3 3 6 6 7 5 6 7 4 2 7 2 2 2 7 6 6 5 7 6 1 7 6 1 6 5 5 7 6 2 6 7 6 1 5 7 6 2 1 3 3 6 6 6 1 2 2 4 6 4 5 7 7 5 7 6 5 1 1 1 1 7 5 6 4 5 4 7 3 6 4 6 4 6 2 5 1 7 6 6 5 1 6 5 6 7 7 2 2 2 5 6 6 5 6 7 5 7 5 5 6 3 6 6 3 3 2 4 6 7 6 6 5 6 5 5 6 7 6 6 6 6 6 5 5 3 7 6 6 7 6 6 3 7 6 6 4 6 7 6 5 7 4 5 5 7 1 5 6 2 6 3 5 7 3 7 7 7 6 6 5 6 6 5 3 2 3 3 4 6 7 6 2 4 6 1 5 1 3 7 6 6 6 6 4 6 3 5 2 6 7 7 1 3 3 6 3 6 7 2 7 7 6 6 6 1
#&gt;  *** Sample cost:  16.62586
#&gt;  *** Number of strata:  6</code></pre>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-47-2.png" width="700"></p>
<pre><code>#&gt; 
#&gt;  *** Sample size :  16
#&gt;  *** Number of strata :  6
#&gt; ---------------------------
sum(solution1$aggr_strata$SOLUZ)
#&gt; [1] 16.62586</code></pre>
<p>Then, we evaluate the expected CV’s on the three variables:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1">newstrata &lt;-<span class="st"> </span><span class="kw"><a href="../reference/updateStrata.html">updateStrata</a></span>(strata1,solution1)</a>
<a class="sourceLine" id="cb58-2" data-line-number="2">framenew1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/updateFrame.html">updateFrame</a></span>(frame,newstrata)</a>
<a class="sourceLine" id="cb58-3" data-line-number="3">framenew1 &lt;-<span class="st"> </span>framenew1[<span class="kw">order</span>(framenew1<span class="op">$</span>ID),]</a>
<a class="sourceLine" id="cb58-4" data-line-number="4">framenew1<span class="op">$</span>Y2 &lt;-<span class="st"> </span>nations<span class="op">$</span>infant.mortality</a>
<a class="sourceLine" id="cb58-5" data-line-number="5">framenew1<span class="op">$</span>Y3 &lt;-<span class="st"> </span>nations<span class="op">$</span>contraception</a>
<a class="sourceLine" id="cb58-6" data-line-number="6">results1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/evalSolution.html">evalSolution</a></span>(framenew1, solution1<span class="op">$</span>aggr_strata, <span class="dv">50</span>, <span class="dt">progress =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb58-7" data-line-number="7">results1<span class="op">$</span>coeff_var</a>
<a class="sourceLine" id="cb58-8" data-line-number="8"><span class="co">#&gt;          CV1       CV2       CV3  dom</span></a>
<a class="sourceLine" id="cb58-9" data-line-number="9"><span class="co">#&gt; 1 0.05332022 0.2326833 0.1431669 DOM1</span></a></code></pre></div>
<p>Clearly, the CV’s on <em>infant mortality</em> and <em>contraception</em> are not compliant with the corresponding precision constraints.</p>
<p>We now proceed in building the <em>strata</em> dataframe using the models:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" data-line-number="1">model &lt;-<span class="st"> </span><span class="ot">NULL</span></a>
<a class="sourceLine" id="cb59-2" data-line-number="2">model<span class="op">$</span>beta[<span class="dv">1</span>] &lt;-<span class="st"> </span>mod_logGDP_INFMORT<span class="op">$</span>coefficients[<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb59-3" data-line-number="3">model<span class="op">$</span>sig2[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="kw">summary</span>(mod_logGDP_INFMORT)<span class="op">$</span>sigma</a>
<a class="sourceLine" id="cb59-4" data-line-number="4">model<span class="op">$</span>type[<span class="dv">1</span>] &lt;-<span class="st"> "loglinear"</span></a>
<a class="sourceLine" id="cb59-5" data-line-number="5">model<span class="op">$</span>gamma[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb59-6" data-line-number="6">model<span class="op">$</span>beta[<span class="dv">2</span>] &lt;-<span class="st"> </span>mod_logGDP_CONTRA<span class="op">$</span>coefficients[<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb59-7" data-line-number="7">model<span class="op">$</span>sig2[<span class="dv">2</span>] &lt;-<span class="st"> </span><span class="kw">summary</span>(mod_logGDP_CONTRA)<span class="op">$</span>sigma</a>
<a class="sourceLine" id="cb59-8" data-line-number="8">model<span class="op">$</span>type[<span class="dv">2</span>] &lt;-<span class="st"> "loglinear"</span></a>
<a class="sourceLine" id="cb59-9" data-line-number="9">model<span class="op">$</span>gamma[<span class="dv">2</span>] &lt;-<span class="st"> </span><span class="dv">0</span></a>
<a class="sourceLine" id="cb59-10" data-line-number="10">model &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(model)</a>
<a class="sourceLine" id="cb59-11" data-line-number="11">model</a>
<a class="sourceLine" id="cb59-12" data-line-number="12"><span class="co">#&gt;         beta      sig2      type gamma</span></a>
<a class="sourceLine" id="cb59-13" data-line-number="13"><span class="co">#&gt; 1 -0.4658038 0.6157600 loglinear     0</span></a>
<a class="sourceLine" id="cb59-14" data-line-number="14"><span class="co">#&gt; 2  0.3464857 0.5593031 loglinear     0</span></a></code></pre></div>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1">strata2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/buildStrataDF.html">buildStrataDF</a></span>(frame, <span class="dt">model =</span> model, <span class="dt">progress =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb60-2" data-line-number="2"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb60-3" data-line-number="3"><span class="co">#&gt; Computations are being done on population data</span></a>
<a class="sourceLine" id="cb60-4" data-line-number="4"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb60-5" data-line-number="5"><span class="co">#&gt; Number of strata:  207</span></a>
<a class="sourceLine" id="cb60-6" data-line-number="6"><span class="co">#&gt; ... of which with only one unit:  207</span></a>
<a class="sourceLine" id="cb60-7" data-line-number="7"><span class="kw">head</span>(strata2)</a>
<a class="sourceLine" id="cb60-8" data-line-number="8"><span class="co">#&gt;   STRATO N          M1        M2          S1        S2 COST CENS DOM1  X1</span></a>
<a class="sourceLine" id="cb60-9" data-line-number="9"><span class="co">#&gt; 1      1 1 0.024595860 15.737965 0.022690436 13.624506    1    0    1   1</span></a>
<a class="sourceLine" id="cb60-10" data-line-number="10"><span class="co">#&gt; 2     10 1 0.009910578 30.945032 0.009142812 26.789408    1    0    1  10</span></a>
<a class="sourceLine" id="cb60-11" data-line-number="11"><span class="co">#&gt; 3    100 1 0.011086660 28.468488 0.010227784 24.645441    1    0    1 100</span></a>
<a class="sourceLine" id="cb60-12" data-line-number="12"><span class="co">#&gt; 4    101 1 0.067027720  7.465936 0.061835128  6.463332    1    0    1 101</span></a>
<a class="sourceLine" id="cb60-13" data-line-number="13"><span class="co">#&gt; 5    102 1 0.064539738  7.678981 0.059539888  6.647767    1    0    1 102</span></a>
<a class="sourceLine" id="cb60-14" data-line-number="14"><span class="co">#&gt; 6    103 1 0.030744575 13.331076 0.028362814 11.540840    1    0    1 103</span></a></code></pre></div>
<p>We proceed with the optimization</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" data-line-number="1">strata2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/buildStrataDF.html">buildStrataDF</a></span>(frame, <span class="dt">model =</span> model, <span class="dt">progress =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb61-2" data-line-number="2"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb61-3" data-line-number="3"><span class="co">#&gt; Computations are being done on population data</span></a>
<a class="sourceLine" id="cb61-4" data-line-number="4"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb61-5" data-line-number="5"><span class="co">#&gt; Number of strata:  207</span></a>
<a class="sourceLine" id="cb61-6" data-line-number="6"><span class="co">#&gt; ... of which with only one unit:  207</span></a>
<a class="sourceLine" id="cb61-7" data-line-number="7">solution2 &lt;-</a>
<a class="sourceLine" id="cb61-8" data-line-number="8"><span class="st">  </span><span class="kw"><a href="../reference/optimizeStrata.html">optimizeStrata</a></span>(</a>
<a class="sourceLine" id="cb61-9" data-line-number="9">    <span class="dt">errors =</span> cv , </a>
<a class="sourceLine" id="cb61-10" data-line-number="10">    <span class="dt">strata =</span> strata2, </a>
<a class="sourceLine" id="cb61-11" data-line-number="11">    <span class="dt">iter =</span> <span class="dv">50</span>, </a>
<a class="sourceLine" id="cb61-12" data-line-number="12">    <span class="dt">pops =</span> <span class="dv">20</span>, </a>
<a class="sourceLine" id="cb61-13" data-line-number="13">    <span class="dt">parallel =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb61-14" data-line-number="14">    <span class="dt">suggestions =</span> <span class="kw"><a href="../reference/KmeansSolution.html">KmeansSolution</a></span>(strata2,cv),</a>
<a class="sourceLine" id="cb61-15" data-line-number="15">    <span class="dt">showPlot =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb61-16" data-line-number="16">    <span class="dt">writeFiles =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-51-1.png" width="700"></p>
<pre><code>#&gt; 
#&gt; -----------------
#&gt;  Kmeans solution 
#&gt; -----------------
#&gt;  *** Domain:  1  ***
#&gt;  Number of strata:  12
#&gt;  Sample size     :  113
#&gt;  *** Domain :  1   1
#&gt;  Number of strata :  207
#&gt; ---------------------------------------------
#&gt; Optimal stratification with Genetic Algorithm
#&gt; ---------------------------------------------
#&gt;  *** Parameters ***
#&gt; ---------------------------
#&gt; Domain:  1
#&gt; Maximum number of strata:  207
#&gt; Minimum number of units per stratum:  2
#&gt; Take-all strata (TRUE/FALSE):  FALSE
#&gt; number of sampling strata :  207
#&gt; Number of target variables:  2
#&gt; Number of domains:  1
#&gt; Number of GA iterations:  50
#&gt; Dimension of GA population:  20
#&gt; Mutation chance in GA generation:  NA
#&gt; Elitism rate in GA generation:  0.2
#&gt; Chance to add strata to maximum:  0
#&gt; Allocation with real numbers instead of integers:  TRUE
#&gt; Suggestion:  12 3 3 4 4 1 12 4 9 6 8 1 8 8 8 1 7 11 6 9 7 5 1 4 5 4 12 12 1 4 8 4 9 2 5 12 1 7 8 5 3 3 4 7 10 5 8 8 6 4 6 12 9 1 12 9 7 12 5 5 3 5 1 12 7 6 12 6 9 3 2 6 10 6 7 8 12 5 9 10 11 12 3 10 12 2 9 1 8 8 8 12 11 11 12 4 1 6 1 12 12 4 3 4 10 3 3 8 6 4 9 9 4 12 7 12 12 10 1 4 10 11 9 7 12 6 3 1 11 7 1 11 10 3 9 4 7 6 10 12 4 12 9 6 12 6 1 5 6 11 8 9 3 12 1 3 1 9 1 4 11 12 11 4 12 8 8 8 3 6 4 1 4 8 6 4 5 12 5 3 1 4 11 10 4 5 10 3 6 8 4 9 1 5 3 3 4 3 10 1 8 9 9 4 10 7 5
#&gt;  *** Sample cost:  108.3405
#&gt;  *** Number of strata:  12</code></pre>
<p><img src="SamplingStrata_files/figure-html/unnamed-chunk-51-2.png" width="700"></p>
<pre><code>#&gt; 
#&gt;  *** Sample size :  108
#&gt;  *** Number of strata :  12
#&gt; ---------------------------</code></pre>
<p>This time the sample size is much higher.</p>
<p>What about the expected CV’s?</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1">newstrata &lt;-<span class="st"> </span><span class="kw"><a href="../reference/updateStrata.html">updateStrata</a></span>(strata2,solution2)</a>
<a class="sourceLine" id="cb64-2" data-line-number="2">framenew2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/updateFrame.html">updateFrame</a></span>(frame,newstrata)</a>
<a class="sourceLine" id="cb64-3" data-line-number="3">framenew2 &lt;-<span class="st"> </span>framenew2[<span class="kw">order</span>(framenew2<span class="op">$</span>ID),]</a>
<a class="sourceLine" id="cb64-4" data-line-number="4">framenew2<span class="op">$</span>Y2 &lt;-<span class="st"> </span>nations<span class="op">$</span>infant.mortality</a>
<a class="sourceLine" id="cb64-5" data-line-number="5">framenew2<span class="op">$</span>Y3 &lt;-<span class="st"> </span>nations<span class="op">$</span>contraception</a>
<a class="sourceLine" id="cb64-6" data-line-number="6">results2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/evalSolution.html">evalSolution</a></span>(framenew2, solution2<span class="op">$</span>aggr_strata, <span class="dv">50</span>, <span class="dt">progress =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb64-7" data-line-number="7">results2<span class="op">$</span>coeff_var</a>
<a class="sourceLine" id="cb64-8" data-line-number="8"><span class="co">#&gt;          CV1        CV2        CV3  dom</span></a>
<a class="sourceLine" id="cb64-9" data-line-number="9"><span class="co">#&gt; 1 0.00566401 0.05020429 0.02625483 DOM1</span></a></code></pre></div>
<p>This time the expected CV’s of all variables are more than compliant with the precision constraints.</p>
</div>
<div id="appendix---methodological-approach" class="section level1">
<h1 class="hasAnchor">
<a href="#appendix---methodological-approach" class="anchor"></a>Appendix - Methodological approach</h1>
<p>In a stratified sampling design with one or more stages, a sample is selected from a frame containing the units of the population of interest, stratified according to the values of one or more auxiliary variables (X) available for all units in the population.</p>
<p>For a given stratification, the overall size of the sample and the allocation in the different strata can be determined on the basis of constraints placed on the expected accuracy of the various estimates regarding the survey variables (Y).</p>
<p>If the target survey variables are more than one the optimization problem is said to be <em>multivariate</em>; otherwise it is <em>univariate</em>.</p>
<p>For a given stratification, in the univariate case the optimization of the allocation is in general based on the <em>Neyman allocation</em>. In the univariate case it is possible to make use of the <em>Bethel algorithm</em>.</p>
<p>The criteria according to which stratification is defined are crucial for the efficiency of the sample.</p>
<p>With the same precision constraints, the overall size of the sample required to satisfy them may be significantly affected by the particular stratification chosen for the population of interest.</p>
<p>Given G survey variables, their sampling variance is:</p>
<p><span class="math display">\[Var(\hat{Y_{g}})=\sum_{h=1}^{H}N_{h}^{2} (1- \frac{ 
  n_{h}}
  {N_{h}}) \frac{ 
  S_{h,g}^{2}}
  {n_{h}} \;\;\;  g=1,...,G\]</span></p>
<p>If we introduce the following cost function:</p>
<p><span class="math display">\[C(n_{1},...,n_{H})=C_{0}+\sum_{h=1}^{H}C_{h}n_{h} \]</span></p>
<p>the optimization problem can be formalized in this way:</p>
<p><span class="math display">\[min= C_{0}+\sum_{h=1}^{H}C_{h}n_{h}\\ \]</span> under the constraints <span class="math display">\[ 
\begin{cases} 
CV(\hat{Y_{1}}) &lt; U_{1}\\ 
CV(\hat{Y_{2}}) &lt; U_{2}\\
...\\
CV(\hat{Y_{G}}) &lt; U_{G}\\
\end{cases}
\]</span> where <span class="math display">\[ CV(\hat{Y_{g}}) = \frac{\sqrt{Var(\hat{Y_{g}})} } {mean(\hat{Y_{g}})}\]</span></p>
<p>Given a population frame with m auxiliary variables <span class="math inline">\(X_{1},..., X_{M}\)</span> we define as <em>atomic stratification</em> the one that can be obtained considering the cartesian product of the definition domains of the m variables. <span class="math display">\[L=\{(l_{1}),(l_{2}),...,(l_{k})\}\]</span> Starting from the atomic stratification, it is possible to generate all the different stratifications that belong to the universe of stratifications. For example:</p>
<p><span class="math display">\[
\begin{align*}
&amp;P_{1}=\{(l_{1},l_{2},l_{3})\} &amp; P_{2}=\{(l_{1}),(l_{2},l_{3})\} \\
&amp;P_{2}=\{(l_{2}),(l_{1},l_{3})\} &amp; P_{4}=\{(l_{31}),(l_{1},l_{2})\} \\
&amp;P_{5}=\{(l_{1}),(l_{2}),(l_{k})\}
\end{align*}
\]</span></p>
<p>The number of feasible stratifications is exponential with respect to the number of initial atomic strata:</p>
<p><span class="math display">\[
\begin{align*}
&amp; B_{4}=15 &amp; B_{10}=115975 &amp;
&amp; B_{100}\approx 4.76 \times 10^{115} 
\end{align*}
\]</span></p>
<p>In concrete cases, it is therefore impossible to examine all the different possible alternative stratifications. The <em>Genetic Algorithm</em> allows to explore the universe of stratification in a very efficient way in order to find the optimal (or close to optimal) solution.</p>
<p>In planning a strafied sampling for a given survey, proceed as follows:</p>
<ul>
<li><p>given the survey variables <span class="math inline">\(Y_{1},Y_{2},...,Y_{p}\)</span>, set <em>precision constraints</em> on their estimates in the different domains, expressed in terms of CVs (coefficients of variation);</p></li>
<li><p>in the available sampling frame build the <em>atomic stratification</em>, obtained as cartesian product of the domains of the auxiliary variables <span class="math inline">\(X_{1},...,X_{M}\)</span>;</p></li>
<li><p>in each atomic stratum report the distributional characteristics of the survey variables by calculating their <em>means</em> and <em>standard deviations</em> calculate the values of the population (directly or by using proxy variables);</p></li>
<li><p>on the basis of these inputs, the Genetic Algorithm determines the <em>best solution</em> in terms of both frame <em>stratification</em>, <em>sample size</em> and <em>allocation</em> in optimized strata.</p></li>
</ul>
<p>The application of the genetic algorithm is based on the following steps:</p>
<ul>
<li><p>a given stratification is considered as an <em>individual</em> in a population (= <em>generation</em>) subject to <em>evolution</em>;</p></li>
<li><p>each individual is characterized by a <em>genome</em> represented by a vector of dimension equal to the number of atomic strata: the position of each element in the vector identifies an atomic stratum;</p></li>
<li><p>each element in the vector is assigned a random value between 1 and K (maximum acceptable number of strata): the vector therefore indicates the way in which the individual atomic strata are aggregated together;</p></li>
<li><p>for each individual (stratification) its <em>fitness</em> is calculated by solving the corresponding problem of optimal allocation by means of Bethel’s algorithm;</p></li>
<li><p>in passing from one generation to the next, <em>individuals with higher fitness are favored</em>;</p></li>
<li><p>at the end of the process of evolution, the individual with the overall best fitness represents the optimal solution.</p></li>
</ul>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-baillargeon:2014">
<p>Baillargeon, Sophie, and Louis-Paul Rivest. 2014. <em>Stratification: Univariate Stratification of Survey Populations</em>. <a href="https://CRAN.R-project.org/package=stratification" class="uri">https://CRAN.R-project.org/package=stratification</a>.</p>
</div>
<div id="ref-ballin:2016">
<p>Ballin, Marco, and Giulio Barcaroli. 2016. “Optimization of Stratified Sampling with the R Package SamplingStrata: Applications to Network Data.” <em>Computational Network Analysis with R: Applications in Biology, Medicine and Chemistry</em>. John Wiley &amp; Sons.</p>
</div>
<div id="ref-ballin:2013">
<p>Ballin, M., and G. Barcaroli. 2013. “Joint Determination of Optimal Stratification and Sample Allocation Using Genetic Algorithm.” <em>Survey Methodology</em> 39: 369–93.</p>
</div>
<div id="ref-barcarol:2013">
<p>Barcaroli, G. 2014. “SamplingStrata: An R Package for the Optimization of Stratified Sampling.” <em>Journal of Statistical Software</em> 61 (4): 1–24. <a href="https://www.jstatsoft.org/article/view/v061i04" class="uri">https://www.jstatsoft.org/article/view/v061i04</a>.</p>
</div>
<div id="ref-hartigan:1979">
<p>Hartigan, J. A., and M. A. Wong. 1979. “A K-Means Clustering Algorithm.” <em>Applied Statistics</em> 28: 100–108.</p>
</div>
<div id="ref-oluing:2017">
<p>O’Luing, M., S. Prestwich, and S. Armagan Tarim. 2017. “Constructing Strata to Solve Sample Allocation Problems by Grouping Genetic Algorithm.” <em>arXiv:1709.03076</em>.</p>
</div>
<div id="ref-willighagen:2005">
<p>Willighagen, E. 2005. <em>Genalg: R Based Genetic Algorithm</em>. <a href="https://CRAN.R-project.org/package=genalg" class="uri">https://CRAN.R-project.org/package=genalg</a>.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li>
<a href="#procedural-steps">Procedural steps</a><ul class="nav nav-pills nav-stacked">
<li><a href="#analysis-of-the-frame-data-and-manipulation-of-auxiliary-information">Analysis of the frame data and manipulation of auxiliary information</a></li>
      <li><a href="#construction-of-atomic-strata-and-association-of-the-information-related-to-target-variables">Construction of atomic strata and association of the information related to target variables</a></li>
      <li><a href="#choice-of-the-precision-constraints-for-each-target-estimate">Choice of the precision constraints for each target estimate</a></li>
      <li><a href="#optimization-of-frame-stratification">Optimization of frame stratification</a></li>
      </ul>
</li>
      <li><a href="#initial-solution-with-kmeans-clustering-of-atomic-strata">Initial solution with kmeans clustering of atomic strata</a></li>
      <li><a href="#adjustment-of-the-final-sampling-size">Adjustment of the final sampling size</a></li>
      <li><a href="#analysis-of-results">Analysis of results</a></li>
      <li><a href="#updating-the-frame-and-selecting-the-sample">Updating the frame and selecting the sample</a></li>
      <li><a href="#evaluation-of-the-found-solution">Evaluation of the found solution</a></li>
      <li><a href="#handling-take-all-strata-in-the-optimization-step">Handling ‘take-all’ strata in the optimization step</a></li>
      <li><a href="#handling-anticipated-variance">Handling Anticipated Variance</a></li>
      <li><a href="#appendix---methodological-approach">Appendix - Methodological approach</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Giulio Barcaroli, Marco Ballin, Hanjo Odendaal, Daniela Pagliuca, Egon Willighagen, Diego Zardetto.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
