# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

select_variables <- function(dati, prefix, nvar) {
    .Call(`_SamplingStrata_select_variables`, dati, prefix, nvar)
}

disjoint <- function(dom) {
    .Call(`_SamplingStrata_disjoint`, dom)
}

m_s <- function(disj, mat) {
    .Call(`_SamplingStrata_m_s`, disj, mat)
}

rowSums_Rcpp <- function(x) {
    .Call(`_SamplingStrata_rowSums_Rcpp`, x)
}

colSums_Rcpp <- function(x) {
    .Call(`_SamplingStrata_colSums_Rcpp`, x)
}

cv_Rcpp <- function(errors, ndom, nvar) {
    .Call(`_SamplingStrata_cv_Rcpp`, errors, ndom, nvar)
}

crea_a <- function(m, s, nocens, N, cv, epsilon) {
    .Call(`_SamplingStrata_crea_a`, m, s, nocens, N, cv, epsilon)
}

chromy_Rcpp <- function(a, alfatot, diff, iter, alfa, alfanext, x, cost, nvar, realAllocation) {
    .Call(`_SamplingStrata_chromy_Rcpp`, a, alfatot, diff, iter, alfa, alfanext, x, cost, nvar, realAllocation)
}

check_n <- function(n, N, minnumstrat) {
    .Call(`_SamplingStrata_check_n`, n, N, minnumstrat)
}

bethel_cpp <- function(strata, errors, minnumstrat, realAllocation = TRUE) {
    .Call(`_SamplingStrata_bethel_cpp`, strata, errors, minnumstrat, realAllocation)
}

buildStrataDF <- function(dataset, model_ = NULL, progress = TRUE, verbose = TRUE) {
    .Call(`_SamplingStrata_buildStrataDF`, dataset, model_, progress, verbose)
}

buildStrataDFSpatial <- function(dataset, fitting = as.numeric( c(1.0)), range = as.numeric( c(0.0)), kappa = 3.0, progress = FALSE, verbose = FALSE) {
    .Call(`_SamplingStrata_buildStrataDFSpatial`, dataset, fitting, range, kappa, progress, verbose)
}

